// DXCC Entity List - Current and Deleted Entities
// Source: ARRL DXCC List (https://www.arrl.org/files/file/DXCC/Current_Deleted.txt)
// Generated: 2026-01-16T00:07:11Z from dxcc_entities.json
//
// This is the authoritative list of DXCC entities as defined by ARRL.
// Total: 402 entities (340 current + 62 deleted)
//
// Entity IDs use ARRL's 3-digit zero-padded string format (e.g., "001" for Canada)
//
// DO NOT MANUALLY EDIT - regenerate using: python scripts/generate_reference.py
//
#![allow(dead_code)]

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub struct DxccEntity {
    pub entity_id: &'static str,  // ARRL 3-digit format: "001", "291", etc.
    pub name: &'static str,
    pub continent: &'static str,
    pub cq_zones: &'static [u8],
    pub itu_zones: &'static [u8],
    pub deleted: bool,
}

/// DXCC entities list from official ARRL data
pub const DXCC_ENTITIES: &[DxccEntity] = &[
    DxccEntity { entity_id: "001", name: "Canada", continent: "NA", cq_zones: &[1, 2, 3, 4, 5], itu_zones: &[], deleted: false },
    DxccEntity { entity_id: "002", name: "Abu Ail Is.", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: true },
    DxccEntity { entity_id: "003", name: "Afghanistan", continent: "AS", cq_zones: &[21], itu_zones: &[40], deleted: false },
    DxccEntity { entity_id: "004", name: "Agalega & St. Brandon Is.", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "005", name: "Aland Is.", continent: "EU", cq_zones: &[15], itu_zones: &[18], deleted: false },
    DxccEntity { entity_id: "006", name: "Alaska", continent: "NA", cq_zones: &[1], itu_zones: &[1, 2], deleted: false },
    DxccEntity { entity_id: "007", name: "Albania", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "008", name: "Aldabra", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: true },
    DxccEntity { entity_id: "009", name: "American Samoa", continent: "OC", cq_zones: &[32], itu_zones: &[62], deleted: false },
    DxccEntity { entity_id: "010", name: "Amsterdam & St. Paul Is.", continent: "AF", cq_zones: &[39], itu_zones: &[68], deleted: false },
    DxccEntity { entity_id: "011", name: "Andaman & Nicobar Is.", continent: "AS", cq_zones: &[26], itu_zones: &[49], deleted: false },
    DxccEntity { entity_id: "012", name: "Anguilla", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "013", name: "Antarctica", continent: "AN", cq_zones: &[], itu_zones: &[], deleted: false },
    DxccEntity { entity_id: "014", name: "Armenia", continent: "AS", cq_zones: &[21], itu_zones: &[29], deleted: false },
    DxccEntity { entity_id: "015", name: "Asiatic Russia", continent: "AS", cq_zones: &[], itu_zones: &[], deleted: false },
    DxccEntity { entity_id: "016", name: "New Zealand Subantarctic Islands", continent: "OC", cq_zones: &[32], itu_zones: &[60], deleted: false },
    DxccEntity { entity_id: "017", name: "Aves I.", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "018", name: "Azerbaijan", continent: "AS", cq_zones: &[21], itu_zones: &[29], deleted: false },
    DxccEntity { entity_id: "019", name: "Bajo Nuevo", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: true },
    DxccEntity { entity_id: "020", name: "Baker & Howland Is.", continent: "OC", cq_zones: &[31], itu_zones: &[61], deleted: false },
    DxccEntity { entity_id: "021", name: "Balearic Is.", continent: "EU", cq_zones: &[14], itu_zones: &[37], deleted: false },
    DxccEntity { entity_id: "022", name: "Palau", continent: "OC", cq_zones: &[27], itu_zones: &[64], deleted: false },
    DxccEntity { entity_id: "023", name: "Blenheim Reef", continent: "AF", cq_zones: &[39], itu_zones: &[41], deleted: true },
    DxccEntity { entity_id: "024", name: "Bouvet", continent: "AF", cq_zones: &[38], itu_zones: &[67], deleted: false },
    DxccEntity { entity_id: "025", name: "British North Borneo", continent: "OC", cq_zones: &[28], itu_zones: &[54], deleted: true },
    DxccEntity { entity_id: "026", name: "British Somaliland", continent: "AF", cq_zones: &[37], itu_zones: &[48], deleted: true },
    DxccEntity { entity_id: "027", name: "Belarus (Republic of)", continent: "EU", cq_zones: &[16], itu_zones: &[29], deleted: false },
    DxccEntity { entity_id: "028", name: "Canal Zone", continent: "NA", cq_zones: &[7], itu_zones: &[11], deleted: true },
    DxccEntity { entity_id: "029", name: "Canary Is.", continent: "AF", cq_zones: &[33], itu_zones: &[36], deleted: false },
    DxccEntity { entity_id: "030", name: "Celebe & Molucca Is.", continent: "OC", cq_zones: &[28], itu_zones: &[54], deleted: true },
    DxccEntity { entity_id: "031", name: "C. Kiribati (British Phoenix Is.)", continent: "OC", cq_zones: &[31], itu_zones: &[62], deleted: false },
    DxccEntity { entity_id: "032", name: "Ceuta & Melilla", continent: "AF", cq_zones: &[33], itu_zones: &[37], deleted: false },
    DxccEntity { entity_id: "033", name: "Chagos Is.", continent: "AF", cq_zones: &[39], itu_zones: &[41], deleted: false },
    DxccEntity { entity_id: "034", name: "Chatham Is.", continent: "OC", cq_zones: &[32], itu_zones: &[60], deleted: false },
    DxccEntity { entity_id: "035", name: "Christmas I.", continent: "OC", cq_zones: &[29], itu_zones: &[54], deleted: false },
    DxccEntity { entity_id: "036", name: "Clipperton I.", continent: "NA", cq_zones: &[7], itu_zones: &[10], deleted: false },
    DxccEntity { entity_id: "037", name: "Cocos I.", continent: "NA", cq_zones: &[7], itu_zones: &[12], deleted: false },
    DxccEntity { entity_id: "038", name: "Cocos (Keeling) Is.", continent: "OC", cq_zones: &[29], itu_zones: &[54], deleted: false },
    DxccEntity { entity_id: "039", name: "Comoros", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: true },
    DxccEntity { entity_id: "040", name: "Crete", continent: "EU", cq_zones: &[20], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "041", name: "Crozet I.", continent: "AF", cq_zones: &[39], itu_zones: &[68], deleted: false },
    DxccEntity { entity_id: "042", name: "Damao, Diu", continent: "AS", cq_zones: &[22], itu_zones: &[41], deleted: true },
    DxccEntity { entity_id: "043", name: "Desecheo I.", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "044", name: "Desroches", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: true },
    DxccEntity { entity_id: "045", name: "Dodecanese", continent: "EU", cq_zones: &[20], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "046", name: "East Malaysia", continent: "OC", cq_zones: &[28], itu_zones: &[54], deleted: false },
    DxccEntity { entity_id: "047", name: "Easter I.", continent: "SA", cq_zones: &[12], itu_zones: &[63], deleted: false },
    DxccEntity { entity_id: "048", name: "E. Kiribati (Line Is.)", continent: "OC", cq_zones: &[31], itu_zones: &[61, 63], deleted: false },
    DxccEntity { entity_id: "049", name: "Equatorial Guinea", continent: "AF", cq_zones: &[36], itu_zones: &[47], deleted: false },
    DxccEntity { entity_id: "050", name: "Mexico", continent: "NA", cq_zones: &[6], itu_zones: &[10], deleted: false },
    DxccEntity { entity_id: "051", name: "Eritrea", continent: "AF", cq_zones: &[37], itu_zones: &[48], deleted: false },
    DxccEntity { entity_id: "052", name: "Estonia", continent: "EU", cq_zones: &[15], itu_zones: &[29], deleted: false },
    DxccEntity { entity_id: "053", name: "Ethiopia", continent: "AF", cq_zones: &[37], itu_zones: &[48], deleted: false },
    DxccEntity { entity_id: "054", name: "European Russia", continent: "EU", cq_zones: &[16], itu_zones: &[], deleted: false },
    DxccEntity { entity_id: "055", name: "Farquhar", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: true },
    DxccEntity { entity_id: "056", name: "Fernando de Noronha", continent: "SA", cq_zones: &[11], itu_zones: &[13], deleted: false },
    DxccEntity { entity_id: "057", name: "French Equatorial Africa", continent: "AF", cq_zones: &[36], itu_zones: &[47, 52], deleted: true },
    DxccEntity { entity_id: "058", name: "French Indo-China", continent: "AS", cq_zones: &[26], itu_zones: &[49], deleted: true },
    DxccEntity { entity_id: "059", name: "French West Africa", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: true },
    DxccEntity { entity_id: "060", name: "Bahamas (Commonwealth of the)", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "061", name: "Franz Josef Land", continent: "EU", cq_zones: &[40], itu_zones: &[75], deleted: false },
    DxccEntity { entity_id: "062", name: "Barbados", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "063", name: "French Guiana", continent: "SA", cq_zones: &[9], itu_zones: &[12], deleted: false },
    DxccEntity { entity_id: "064", name: "Bermuda", continent: "NA", cq_zones: &[5], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "065", name: "British Virgin Is.", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "066", name: "Belize", continent: "NA", cq_zones: &[7], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "067", name: "French India", continent: "AS", cq_zones: &[22], itu_zones: &[41], deleted: true },
    DxccEntity { entity_id: "068", name: "Kuwait/Saudi Arabia Neutral Zone", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: true },
    DxccEntity { entity_id: "069", name: "Cayman Is.", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "070", name: "Cuba", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "071", name: "Galapagos Is.", continent: "SA", cq_zones: &[10], itu_zones: &[12], deleted: false },
    DxccEntity { entity_id: "072", name: "Dominican Republic", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "074", name: "El Salvador", continent: "NA", cq_zones: &[7], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "075", name: "Georgia", continent: "AS", cq_zones: &[21], itu_zones: &[29], deleted: false },
    DxccEntity { entity_id: "076", name: "Guatemala", continent: "NA", cq_zones: &[7], itu_zones: &[12], deleted: false },
    DxccEntity { entity_id: "077", name: "Grenada", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "078", name: "Haiti", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "079", name: "Guadeloupe", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "080", name: "Honduras", continent: "NA", cq_zones: &[7], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "081", name: "Germany", continent: "EU", cq_zones: &[14], itu_zones: &[28], deleted: true },
    DxccEntity { entity_id: "082", name: "Jamaica", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "084", name: "Martinique", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "085", name: "Bonaire, Curacao", continent: "SA", cq_zones: &[9], itu_zones: &[11], deleted: true },
    DxccEntity { entity_id: "086", name: "Nicaragua", continent: "NA", cq_zones: &[7], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "088", name: "Panama", continent: "NA", cq_zones: &[7], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "089", name: "Turks & Caicos Is.", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "090", name: "Trinidad & Tobago", continent: "SA", cq_zones: &[9], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "091", name: "Aruba", continent: "SA", cq_zones: &[9], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "093", name: "Geyser Reef", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: true },
    DxccEntity { entity_id: "094", name: "Antigua & Barbuda", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "095", name: "Dominica", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "096", name: "Montserrat", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "097", name: "St. Lucia", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "098", name: "St. Vincent", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "099", name: "Glorioso Is.", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "100", name: "Argentina", continent: "SA", cq_zones: &[13], itu_zones: &[14, 16], deleted: false },
    DxccEntity { entity_id: "101", name: "Goa", continent: "AS", cq_zones: &[22], itu_zones: &[41], deleted: true },
    DxccEntity { entity_id: "102", name: "Gold Coast, Togoland", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: true },
    DxccEntity { entity_id: "103", name: "Guam", continent: "OC", cq_zones: &[27], itu_zones: &[64], deleted: false },
    DxccEntity { entity_id: "104", name: "Bolivia", continent: "SA", cq_zones: &[10], itu_zones: &[12, 14], deleted: false },
    DxccEntity { entity_id: "105", name: "Guantanamo Bay", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "106", name: "Guernsey", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "107", name: "Guinea", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "108", name: "Brazil", continent: "SA", cq_zones: &[11], itu_zones: &[], deleted: false },
    DxccEntity { entity_id: "109", name: "Guinea-Bissau", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "110", name: "Hawaii", continent: "OC", cq_zones: &[31], itu_zones: &[61], deleted: false },
    DxccEntity { entity_id: "111", name: "Heard I.", continent: "AF", cq_zones: &[39], itu_zones: &[68], deleted: false },
    DxccEntity { entity_id: "112", name: "Chile", continent: "SA", cq_zones: &[12], itu_zones: &[14, 16], deleted: false },
    DxccEntity { entity_id: "113", name: "Ifni", continent: "AF", cq_zones: &[33], itu_zones: &[37], deleted: true },
    DxccEntity { entity_id: "114", name: "Isle of Man", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "115", name: "Italian Somaliland", continent: "AF", cq_zones: &[37], itu_zones: &[48], deleted: true },
    DxccEntity { entity_id: "116", name: "Colombia", continent: "SA", cq_zones: &[9], itu_zones: &[12], deleted: false },
    DxccEntity { entity_id: "117", name: "ITU HQ", continent: "EU", cq_zones: &[14], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "118", name: "Jan Mayen", continent: "EU", cq_zones: &[40], itu_zones: &[18], deleted: false },
    DxccEntity { entity_id: "119", name: "Java", continent: "OC", cq_zones: &[28], itu_zones: &[54], deleted: true },
    DxccEntity { entity_id: "120", name: "Ecuador", continent: "SA", cq_zones: &[10], itu_zones: &[12], deleted: false },
    DxccEntity { entity_id: "122", name: "Jersey", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "123", name: "Johnston I.", continent: "OC", cq_zones: &[31], itu_zones: &[61], deleted: false },
    DxccEntity { entity_id: "124", name: "Juan de Nova, Europa", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "125", name: "Juan Fernandez Is.", continent: "SA", cq_zones: &[12], itu_zones: &[14], deleted: false },
    DxccEntity { entity_id: "126", name: "Kaliningrad", continent: "EU", cq_zones: &[15], itu_zones: &[29], deleted: false },
    DxccEntity { entity_id: "127", name: "Kamaran Is.", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: true },
    DxccEntity { entity_id: "128", name: "Karelo-Finnish Republic", continent: "EU", cq_zones: &[16], itu_zones: &[19], deleted: true },
    DxccEntity { entity_id: "129", name: "Guyana", continent: "SA", cq_zones: &[9], itu_zones: &[12], deleted: false },
    DxccEntity { entity_id: "130", name: "Kazakhstan", continent: "AS", cq_zones: &[17], itu_zones: &[29, 30, 31], deleted: false },
    DxccEntity { entity_id: "131", name: "Kerguelen Is.", continent: "AF", cq_zones: &[39], itu_zones: &[68], deleted: false },
    DxccEntity { entity_id: "132", name: "Paraguay", continent: "SA", cq_zones: &[11], itu_zones: &[14], deleted: false },
    DxccEntity { entity_id: "133", name: "Kermadec Is.", continent: "OC", cq_zones: &[32], itu_zones: &[60], deleted: false },
    DxccEntity { entity_id: "134", name: "Kingman Reef", continent: "OC", cq_zones: &[31], itu_zones: &[61], deleted: true },
    DxccEntity { entity_id: "135", name: "Kyrgyz Republic", continent: "AS", cq_zones: &[17], itu_zones: &[30, 31], deleted: false },
    DxccEntity { entity_id: "136", name: "Peru", continent: "SA", cq_zones: &[10], itu_zones: &[12], deleted: false },
    DxccEntity { entity_id: "137", name: "Korea (Republic of)", continent: "AS", cq_zones: &[25], itu_zones: &[44], deleted: false },
    DxccEntity { entity_id: "138", name: "Kure I.", continent: "OC", cq_zones: &[31], itu_zones: &[61], deleted: false },
    DxccEntity { entity_id: "139", name: "Kuria Muria I.", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: true },
    DxccEntity { entity_id: "140", name: "Suriname", continent: "SA", cq_zones: &[9], itu_zones: &[12], deleted: false },
    DxccEntity { entity_id: "141", name: "Falkland Is.", continent: "SA", cq_zones: &[13], itu_zones: &[16], deleted: false },
    DxccEntity { entity_id: "142", name: "Lakshadweep Is.", continent: "AS", cq_zones: &[22], itu_zones: &[41], deleted: false },
    DxccEntity { entity_id: "143", name: "Lao People's Democratic Rep", continent: "AS", cq_zones: &[26], itu_zones: &[49], deleted: false },
    DxccEntity { entity_id: "144", name: "Uruguay", continent: "SA", cq_zones: &[13], itu_zones: &[14], deleted: false },
    DxccEntity { entity_id: "145", name: "Latvia", continent: "EU", cq_zones: &[15], itu_zones: &[29], deleted: false },
    DxccEntity { entity_id: "146", name: "Lithuania", continent: "EU", cq_zones: &[15], itu_zones: &[29], deleted: false },
    DxccEntity { entity_id: "147", name: "Lord Howe I.", continent: "OC", cq_zones: &[30], itu_zones: &[60], deleted: false },
    DxccEntity { entity_id: "148", name: "Venezuela", continent: "SA", cq_zones: &[9], itu_zones: &[12], deleted: false },
    DxccEntity { entity_id: "149", name: "Azores", continent: "EU", cq_zones: &[14], itu_zones: &[36], deleted: false },
    DxccEntity { entity_id: "150", name: "Australia", continent: "OC", cq_zones: &[29, 30], itu_zones: &[], deleted: false },
    DxccEntity { entity_id: "151", name: "Malyj Vysotskij I.", continent: "EU", cq_zones: &[16], itu_zones: &[29], deleted: true },
    DxccEntity { entity_id: "152", name: "Macao", continent: "AS", cq_zones: &[24], itu_zones: &[44], deleted: false },
    DxccEntity { entity_id: "153", name: "Macquarie I.", continent: "OC", cq_zones: &[30], itu_zones: &[60], deleted: false },
    DxccEntity { entity_id: "154", name: "Yemen Arab Republic", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: true },
    DxccEntity { entity_id: "155", name: "Malaya", continent: "AS", cq_zones: &[28], itu_zones: &[54], deleted: true },
    DxccEntity { entity_id: "157", name: "Nauru", continent: "OC", cq_zones: &[31], itu_zones: &[65], deleted: false },
    DxccEntity { entity_id: "158", name: "Vanuatu", continent: "OC", cq_zones: &[32], itu_zones: &[56], deleted: false },
    DxccEntity { entity_id: "159", name: "Maldives", continent: "AS", cq_zones: &[22], itu_zones: &[41], deleted: false },
    DxccEntity { entity_id: "160", name: "Tonga", continent: "OC", cq_zones: &[32], itu_zones: &[62], deleted: false },
    DxccEntity { entity_id: "161", name: "Malpelo I.", continent: "SA", cq_zones: &[9], itu_zones: &[12], deleted: false },
    DxccEntity { entity_id: "162", name: "New Caledonia", continent: "OC", cq_zones: &[32], itu_zones: &[56], deleted: false },
    DxccEntity { entity_id: "163", name: "Papua New Guinea", continent: "OC", cq_zones: &[28], itu_zones: &[51], deleted: false },
    DxccEntity { entity_id: "164", name: "Manchuria", continent: "AS", cq_zones: &[24], itu_zones: &[33], deleted: true },
    DxccEntity { entity_id: "165", name: "Mauritius", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "166", name: "Mariana Is.", continent: "OC", cq_zones: &[27], itu_zones: &[64], deleted: false },
    DxccEntity { entity_id: "167", name: "Market Reef", continent: "EU", cq_zones: &[15], itu_zones: &[18], deleted: false },
    DxccEntity { entity_id: "168", name: "Marshall Is.", continent: "OC", cq_zones: &[31], itu_zones: &[65], deleted: false },
    DxccEntity { entity_id: "169", name: "Mayotte", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "170", name: "New Zealand", continent: "OC", cq_zones: &[32], itu_zones: &[60], deleted: false },
    DxccEntity { entity_id: "171", name: "Mellish Reef", continent: "OC", cq_zones: &[30], itu_zones: &[56], deleted: false },
    DxccEntity { entity_id: "172", name: "Pitcairn I.", continent: "OC", cq_zones: &[32], itu_zones: &[63], deleted: false },
    DxccEntity { entity_id: "173", name: "Micronesia", continent: "OC", cq_zones: &[27], itu_zones: &[65], deleted: false },
    DxccEntity { entity_id: "174", name: "Midway I.", continent: "OC", cq_zones: &[31], itu_zones: &[61], deleted: false },
    DxccEntity { entity_id: "175", name: "French Polynesia", continent: "OC", cq_zones: &[32], itu_zones: &[63], deleted: false },
    DxccEntity { entity_id: "176", name: "Fiji (Republic of)", continent: "OC", cq_zones: &[32], itu_zones: &[56], deleted: false },
    DxccEntity { entity_id: "177", name: "Minami Torishima", continent: "OC", cq_zones: &[27], itu_zones: &[90], deleted: false },
    DxccEntity { entity_id: "178", name: "Minerva Reef", continent: "OC", cq_zones: &[32], itu_zones: &[62], deleted: true },
    DxccEntity { entity_id: "179", name: "Moldova (Republic of)", continent: "EU", cq_zones: &[16], itu_zones: &[29], deleted: false },
    DxccEntity { entity_id: "180", name: "Mount Athos", continent: "EU", cq_zones: &[20], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "181", name: "Mozambique", continent: "AF", cq_zones: &[37], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "182", name: "Navassa I.", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "183", name: "Netherlands Borneo", continent: "OC", cq_zones: &[28], itu_zones: &[54], deleted: true },
    DxccEntity { entity_id: "184", name: "Netherlands New Guinea", continent: "OC", cq_zones: &[28], itu_zones: &[51], deleted: true },
    DxccEntity { entity_id: "185", name: "Solomon Is.", continent: "OC", cq_zones: &[28], itu_zones: &[51], deleted: false },
    DxccEntity { entity_id: "186", name: "Newfoundland, Labrador", continent: "NA", cq_zones: &[2, 5], itu_zones: &[9], deleted: true },
    DxccEntity { entity_id: "187", name: "Niger", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "188", name: "Niue", continent: "OC", cq_zones: &[32], itu_zones: &[62], deleted: false },
    DxccEntity { entity_id: "189", name: "Norfolk I.", continent: "OC", cq_zones: &[32], itu_zones: &[60], deleted: false },
    DxccEntity { entity_id: "190", name: "Samoa", continent: "OC", cq_zones: &[32], itu_zones: &[62], deleted: false },
    DxccEntity { entity_id: "191", name: "North Cook Is.", continent: "OC", cq_zones: &[32], itu_zones: &[62], deleted: false },
    DxccEntity { entity_id: "192", name: "Ogasawara", continent: "AS", cq_zones: &[27], itu_zones: &[45], deleted: false },
    DxccEntity { entity_id: "193", name: "Okinawa (Ryukyu Is.)", continent: "AS", cq_zones: &[25], itu_zones: &[45], deleted: true },
    DxccEntity { entity_id: "194", name: "Okino Tori-shima", continent: "AS", cq_zones: &[27], itu_zones: &[45], deleted: true },
    DxccEntity { entity_id: "195", name: "Annobon I.", continent: "AF", cq_zones: &[36], itu_zones: &[52], deleted: false },
    DxccEntity { entity_id: "196", name: "Palestine", continent: "AS", cq_zones: &[20], itu_zones: &[39], deleted: true },
    DxccEntity { entity_id: "197", name: "Palmyra & Jarvis Is.", continent: "OC", cq_zones: &[31], itu_zones: &[61, 62], deleted: false },
    DxccEntity { entity_id: "198", name: "Papua Territory", continent: "OC", cq_zones: &[28], itu_zones: &[51], deleted: true },
    DxccEntity { entity_id: "199", name: "Peter 1 I.", continent: "AN", cq_zones: &[12], itu_zones: &[72], deleted: false },
    DxccEntity { entity_id: "200", name: "Portuguese Timor", continent: "OC", cq_zones: &[28], itu_zones: &[54], deleted: true },
    DxccEntity { entity_id: "201", name: "Prince Edward & Marion Is.", continent: "AF", cq_zones: &[38], itu_zones: &[57], deleted: false },
    DxccEntity { entity_id: "202", name: "Puerto Rico", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "203", name: "Andorra", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "204", name: "Revillagigedo", continent: "NA", cq_zones: &[6], itu_zones: &[10], deleted: false },
    DxccEntity { entity_id: "205", name: "Ascension I.", continent: "AF", cq_zones: &[36], itu_zones: &[66], deleted: false },
    DxccEntity { entity_id: "206", name: "Austria", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "207", name: "Rodrigues I.", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "208", name: "Ruanda-Urundi", continent: "AF", cq_zones: &[36], itu_zones: &[52], deleted: true },
    DxccEntity { entity_id: "209", name: "Belgium", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "210", name: "Saar", continent: "EU", cq_zones: &[14], itu_zones: &[28], deleted: true },
    DxccEntity { entity_id: "211", name: "Sable I.", continent: "NA", cq_zones: &[5], itu_zones: &[9], deleted: false },
    DxccEntity { entity_id: "212", name: "Bulgaria", continent: "EU", cq_zones: &[20], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "213", name: "Saint Martin", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "214", name: "Corsica", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "215", name: "Cyprus", continent: "AS", cq_zones: &[20], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "216", name: "San Andres & Providencia", continent: "NA", cq_zones: &[7], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "217", name: "San Felix & San Ambrosio", continent: "SA", cq_zones: &[12], itu_zones: &[14], deleted: false },
    DxccEntity { entity_id: "218", name: "Czechoslovakia", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: true },
    DxccEntity { entity_id: "219", name: "Sao Tome & Principe", continent: "AF", cq_zones: &[36], itu_zones: &[47], deleted: false },
    DxccEntity { entity_id: "220", name: "Sarawak", continent: "OC", cq_zones: &[28], itu_zones: &[54], deleted: true },
    DxccEntity { entity_id: "221", name: "Denmark", continent: "EU", cq_zones: &[14], itu_zones: &[18], deleted: false },
    DxccEntity { entity_id: "222", name: "Faroe Is.", continent: "EU", cq_zones: &[14], itu_zones: &[18], deleted: false },
    DxccEntity { entity_id: "223", name: "United Kingdom of Great Britain", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "224", name: "Finland", continent: "EU", cq_zones: &[15], itu_zones: &[18], deleted: false },
    DxccEntity { entity_id: "225", name: "Sardinia", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "226", name: "Saudi Arabia/Iraq Neutral Zone", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: true },
    DxccEntity { entity_id: "227", name: "France", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "228", name: "Serrana Bank & Roncador Cay", continent: "NA", cq_zones: &[7], itu_zones: &[11], deleted: true },
    DxccEntity { entity_id: "229", name: "German Democratic Republic", continent: "EU", cq_zones: &[14], itu_zones: &[28], deleted: true },
    DxccEntity { entity_id: "230", name: "Germany (Federal Rep of)", continent: "EU", cq_zones: &[14], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "231", name: "Sikkim", continent: "AS", cq_zones: &[22], itu_zones: &[41], deleted: true },
    DxccEntity { entity_id: "232", name: "Somalia", continent: "AF", cq_zones: &[37], itu_zones: &[48], deleted: false },
    DxccEntity { entity_id: "233", name: "Gibraltar", continent: "EU", cq_zones: &[14], itu_zones: &[37], deleted: false },
    DxccEntity { entity_id: "234", name: "South Cook Is.", continent: "OC", cq_zones: &[32], itu_zones: &[62], deleted: false },
    DxccEntity { entity_id: "235", name: "South Georgia I.", continent: "SA", cq_zones: &[13], itu_zones: &[73], deleted: false },
    DxccEntity { entity_id: "236", name: "Greece", continent: "EU", cq_zones: &[20], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "237", name: "Greenland", continent: "NA", cq_zones: &[40], itu_zones: &[5, 75], deleted: false },
    DxccEntity { entity_id: "238", name: "South Orkney Is.", continent: "SA", cq_zones: &[13], itu_zones: &[73], deleted: false },
    DxccEntity { entity_id: "239", name: "Hungary", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "240", name: "South Sandwich Is.", continent: "SA", cq_zones: &[13], itu_zones: &[73], deleted: false },
    DxccEntity { entity_id: "241", name: "South Shetland Is.", continent: "SA", cq_zones: &[13], itu_zones: &[73], deleted: false },
    DxccEntity { entity_id: "242", name: "Iceland", continent: "EU", cq_zones: &[40], itu_zones: &[17], deleted: false },
    DxccEntity { entity_id: "243", name: "People's Democratic Rep. of Yemen", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: true },
    DxccEntity { entity_id: "244", name: "Southern Sudan", continent: "AF", cq_zones: &[34], itu_zones: &[47, 48], deleted: true },
    DxccEntity { entity_id: "245", name: "Ireland", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "246", name: "Sovereign Military Order of Malta", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "247", name: "Spratly Is.", continent: "AS", cq_zones: &[26], itu_zones: &[50], deleted: false },
    DxccEntity { entity_id: "248", name: "Italy", continent: "EU", cq_zones: &[15, 33], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "249", name: "St. Kitts & Nevis", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "250", name: "St. Helena", continent: "AF", cq_zones: &[36], itu_zones: &[66], deleted: false },
    DxccEntity { entity_id: "251", name: "Liechtenstein", continent: "EU", cq_zones: &[14], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "252", name: "St. Paul I.", continent: "NA", cq_zones: &[5], itu_zones: &[9], deleted: false },
    DxccEntity { entity_id: "253", name: "St. Peter & St. Paul Rocks", continent: "SA", cq_zones: &[11], itu_zones: &[13], deleted: false },
    DxccEntity { entity_id: "254", name: "Luxembourg", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "255", name: "St. Maarten, Saba, St. Eustatius", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: true },
    DxccEntity { entity_id: "256", name: "Madeira Is.", continent: "AF", cq_zones: &[33], itu_zones: &[36], deleted: false },
    DxccEntity { entity_id: "257", name: "Malta", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "258", name: "Sumatra", continent: "OC", cq_zones: &[28], itu_zones: &[54], deleted: true },
    DxccEntity { entity_id: "259", name: "Svalbard", continent: "EU", cq_zones: &[40], itu_zones: &[18], deleted: false },
    DxccEntity { entity_id: "260", name: "Monaco", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "261", name: "Swan Is.", continent: "NA", cq_zones: &[7], itu_zones: &[11], deleted: true },
    DxccEntity { entity_id: "262", name: "Tajikistan", continent: "AS", cq_zones: &[17], itu_zones: &[30], deleted: false },
    DxccEntity { entity_id: "263", name: "Netherlands", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "264", name: "Tangier", continent: "AF", cq_zones: &[33], itu_zones: &[37], deleted: true },
    DxccEntity { entity_id: "265", name: "Northern Ireland", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "266", name: "Norway", continent: "EU", cq_zones: &[14], itu_zones: &[18], deleted: false },
    DxccEntity { entity_id: "267", name: "Territory of New Guinea", continent: "OC", cq_zones: &[28], itu_zones: &[51], deleted: true },
    DxccEntity { entity_id: "268", name: "Tibet", continent: "AS", cq_zones: &[23], itu_zones: &[41], deleted: true },
    DxccEntity { entity_id: "269", name: "Poland", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "270", name: "Tokelau Is.", continent: "OC", cq_zones: &[31], itu_zones: &[62], deleted: false },
    DxccEntity { entity_id: "271", name: "Trieste", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: true },
    DxccEntity { entity_id: "272", name: "Portugal", continent: "EU", cq_zones: &[14], itu_zones: &[37], deleted: false },
    DxccEntity { entity_id: "273", name: "Trindade & Martim Vaz Is.", continent: "SA", cq_zones: &[11], itu_zones: &[15], deleted: false },
    DxccEntity { entity_id: "274", name: "Tristan da Cunha & Gough I.", continent: "AF", cq_zones: &[38], itu_zones: &[66], deleted: false },
    DxccEntity { entity_id: "275", name: "Romania", continent: "EU", cq_zones: &[20], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "276", name: "Tromelin I.", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "277", name: "St. Pierre & Miquelon", continent: "NA", cq_zones: &[5], itu_zones: &[9], deleted: false },
    DxccEntity { entity_id: "278", name: "San Marino", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "279", name: "Scotland", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "280", name: "Turkmenistan", continent: "AS", cq_zones: &[17], itu_zones: &[30], deleted: false },
    DxccEntity { entity_id: "281", name: "Spain", continent: "EU", cq_zones: &[14], itu_zones: &[37], deleted: false },
    DxccEntity { entity_id: "282", name: "Tuvalu", continent: "OC", cq_zones: &[31], itu_zones: &[65], deleted: false },
    DxccEntity { entity_id: "283", name: "UK Sovereign Base Areas on Cyprus", continent: "AS", cq_zones: &[20], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "284", name: "Sweden", continent: "EU", cq_zones: &[14], itu_zones: &[18], deleted: false },
    DxccEntity { entity_id: "285", name: "Virgin Is.", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "286", name: "Uganda", continent: "AF", cq_zones: &[37], itu_zones: &[48], deleted: false },
    DxccEntity { entity_id: "287", name: "Switzerland", continent: "EU", cq_zones: &[14], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "288", name: "Ukraine", continent: "EU", cq_zones: &[16], itu_zones: &[29], deleted: false },
    DxccEntity { entity_id: "289", name: "United Nations HQ", continent: "NA", cq_zones: &[5], itu_zones: &[8], deleted: false },
    DxccEntity { entity_id: "291", name: "United States of America", continent: "NA", cq_zones: &[3, 4, 5], itu_zones: &[6, 7, 8], deleted: false },
    DxccEntity { entity_id: "292", name: "Uzbekistan", continent: "AS", cq_zones: &[17], itu_zones: &[30], deleted: false },
    DxccEntity { entity_id: "293", name: "Viet Nam", continent: "AS", cq_zones: &[26], itu_zones: &[49], deleted: false },
    DxccEntity { entity_id: "294", name: "Wales", continent: "EU", cq_zones: &[14], itu_zones: &[27], deleted: false },
    DxccEntity { entity_id: "295", name: "Vatican", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "296", name: "Serbia", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "297", name: "Wake I.", continent: "OC", cq_zones: &[31], itu_zones: &[65], deleted: false },
    DxccEntity { entity_id: "298", name: "Wallis & Futuna Is.", continent: "OC", cq_zones: &[32], itu_zones: &[62], deleted: false },
    DxccEntity { entity_id: "299", name: "West Malaysia", continent: "AS", cq_zones: &[28], itu_zones: &[54], deleted: false },
    DxccEntity { entity_id: "301", name: "W. Kiribati (Gilbert Is. )", continent: "OC", cq_zones: &[31], itu_zones: &[65], deleted: false },
    DxccEntity { entity_id: "302", name: "Western Sahara", continent: "AF", cq_zones: &[33], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "303", name: "Willis I.", continent: "OC", cq_zones: &[30], itu_zones: &[55], deleted: false },
    DxccEntity { entity_id: "304", name: "Bahrain", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "305", name: "Bangladesh", continent: "AS", cq_zones: &[22], itu_zones: &[41], deleted: false },
    DxccEntity { entity_id: "306", name: "Bhutan", continent: "AS", cq_zones: &[22], itu_zones: &[41], deleted: false },
    DxccEntity { entity_id: "307", name: "Zanzibar", continent: "AF", cq_zones: &[37], itu_zones: &[53], deleted: true },
    DxccEntity { entity_id: "308", name: "Costa Rica", continent: "NA", cq_zones: &[7], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "309", name: "Myanmar", continent: "AS", cq_zones: &[26], itu_zones: &[49], deleted: false },
    DxccEntity { entity_id: "312", name: "Cambodia", continent: "AS", cq_zones: &[26], itu_zones: &[49], deleted: false },
    DxccEntity { entity_id: "315", name: "Sri Lanka", continent: "AS", cq_zones: &[22], itu_zones: &[41], deleted: false },
    DxccEntity { entity_id: "318", name: "China", continent: "AS", cq_zones: &[23, 24], itu_zones: &[], deleted: false },
    DxccEntity { entity_id: "321", name: "Hong Kong", continent: "AS", cq_zones: &[24], itu_zones: &[44], deleted: false },
    DxccEntity { entity_id: "324", name: "India", continent: "AS", cq_zones: &[22], itu_zones: &[41], deleted: false },
    DxccEntity { entity_id: "327", name: "Indonesia", continent: "OC", cq_zones: &[28], itu_zones: &[51, 54], deleted: false },
    DxccEntity { entity_id: "330", name: "Iran (Islamic Repub of)", continent: "AS", cq_zones: &[21], itu_zones: &[40], deleted: false },
    DxccEntity { entity_id: "333", name: "Iraq", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "336", name: "Israel", continent: "AS", cq_zones: &[20], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "339", name: "Japan", continent: "AS", cq_zones: &[25], itu_zones: &[45], deleted: false },
    DxccEntity { entity_id: "342", name: "Jordan", continent: "AS", cq_zones: &[20], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "344", name: "Democratic People's Rep. of Korea", continent: "AS", cq_zones: &[25], itu_zones: &[44], deleted: false },
    DxccEntity { entity_id: "345", name: "Brunei Darussalam", continent: "OC", cq_zones: &[28], itu_zones: &[54], deleted: false },
    DxccEntity { entity_id: "348", name: "Kuwait", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "354", name: "Lebanon", continent: "AS", cq_zones: &[20], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "363", name: "Mongolia", continent: "AS", cq_zones: &[23], itu_zones: &[32, 33], deleted: false },
    DxccEntity { entity_id: "369", name: "Nepal", continent: "AS", cq_zones: &[22], itu_zones: &[42], deleted: false },
    DxccEntity { entity_id: "370", name: "Oman", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "372", name: "Pakistan (Islamic Rep of)", continent: "AS", cq_zones: &[21], itu_zones: &[41], deleted: false },
    DxccEntity { entity_id: "375", name: "Philippines", continent: "OC", cq_zones: &[27], itu_zones: &[50], deleted: false },
    DxccEntity { entity_id: "376", name: "Qatar", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "378", name: "Saudi Arabia", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "379", name: "Seychelles", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "381", name: "Singapore (Republic of)", continent: "AS", cq_zones: &[28], itu_zones: &[54], deleted: false },
    DxccEntity { entity_id: "382", name: "Djibouti", continent: "AF", cq_zones: &[37], itu_zones: &[48], deleted: false },
    DxccEntity { entity_id: "384", name: "Syrian Arab Republic", continent: "AS", cq_zones: &[20], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "386", name: "Taiwan", continent: "AS", cq_zones: &[24], itu_zones: &[44], deleted: false },
    DxccEntity { entity_id: "387", name: "Thailand", continent: "AS", cq_zones: &[26], itu_zones: &[49], deleted: false },
    DxccEntity { entity_id: "390", name: "Republic of Turkiye", continent: "EU", cq_zones: &[20], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "391", name: "United Arab Emirates", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "400", name: "Algeria (People's Dem Rep of)", continent: "AF", cq_zones: &[33], itu_zones: &[37], deleted: false },
    DxccEntity { entity_id: "401", name: "Angola", continent: "AF", cq_zones: &[36], itu_zones: &[52], deleted: false },
    DxccEntity { entity_id: "402", name: "Botswana (Republic of)", continent: "AF", cq_zones: &[38], itu_zones: &[57], deleted: false },
    DxccEntity { entity_id: "404", name: "Burundi", continent: "AF", cq_zones: &[36], itu_zones: &[52], deleted: false },
    DxccEntity { entity_id: "406", name: "Cameroon", continent: "AF", cq_zones: &[36], itu_zones: &[47], deleted: false },
    DxccEntity { entity_id: "408", name: "Central Africa", continent: "AF", cq_zones: &[36], itu_zones: &[47], deleted: false },
    DxccEntity { entity_id: "409", name: "Cabo Verde (Rep of)", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "410", name: "Chad", continent: "AF", cq_zones: &[36], itu_zones: &[47], deleted: false },
    DxccEntity { entity_id: "411", name: "Comoros", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "412", name: "Republic of the Congo", continent: "AF", cq_zones: &[36], itu_zones: &[52], deleted: false },
    DxccEntity { entity_id: "414", name: "Democratic Republic of the Congo", continent: "AF", cq_zones: &[36], itu_zones: &[52], deleted: false },
    DxccEntity { entity_id: "416", name: "Benin", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "420", name: "Gabon", continent: "AF", cq_zones: &[36], itu_zones: &[52], deleted: false },
    DxccEntity { entity_id: "422", name: "Gambia (Republic of the)", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "424", name: "Ghana", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "428", name: "Cote d'Ivoire", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "430", name: "Kenya", continent: "AF", cq_zones: &[37], itu_zones: &[48], deleted: false },
    DxccEntity { entity_id: "432", name: "Lesotho", continent: "AF", cq_zones: &[38], itu_zones: &[57], deleted: false },
    DxccEntity { entity_id: "434", name: "Liberia", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "436", name: "Libya", continent: "AF", cq_zones: &[34], itu_zones: &[38], deleted: false },
    DxccEntity { entity_id: "438", name: "Madagascar", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "440", name: "Malawi", continent: "AF", cq_zones: &[37], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "442", name: "Mali", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "444", name: "Mauritania", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "446", name: "Morocco (Kingdom of)", continent: "AF", cq_zones: &[33], itu_zones: &[37], deleted: false },
    DxccEntity { entity_id: "450", name: "Nigeria", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "452", name: "Zimbabwe", continent: "AF", cq_zones: &[38], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "453", name: "Reunion I.", continent: "AF", cq_zones: &[39], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "454", name: "Rwanda", continent: "AF", cq_zones: &[36], itu_zones: &[52], deleted: false },
    DxccEntity { entity_id: "456", name: "Senegal", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "458", name: "Sierra Leone", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "460", name: "Rotuma I.", continent: "OC", cq_zones: &[32], itu_zones: &[56], deleted: false },
    DxccEntity { entity_id: "462", name: "South Africa", continent: "AF", cq_zones: &[38], itu_zones: &[57], deleted: false },
    DxccEntity { entity_id: "464", name: "Namibia", continent: "AF", cq_zones: &[38], itu_zones: &[57], deleted: false },
    DxccEntity { entity_id: "466", name: "Sudan", continent: "AF", cq_zones: &[34], itu_zones: &[47, 48], deleted: false },
    DxccEntity { entity_id: "468", name: "Kingdom of Eswatini", continent: "AF", cq_zones: &[38], itu_zones: &[57], deleted: false },
    DxccEntity { entity_id: "470", name: "Tanzania (United Republic of)", continent: "AF", cq_zones: &[37], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "474", name: "Tunisia", continent: "AF", cq_zones: &[33], itu_zones: &[37], deleted: false },
    DxccEntity { entity_id: "478", name: "Egypt", continent: "AF", cq_zones: &[34], itu_zones: &[38], deleted: false },
    DxccEntity { entity_id: "480", name: "Burkina Faso", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "482", name: "Zambia", continent: "AF", cq_zones: &[36], itu_zones: &[53], deleted: false },
    DxccEntity { entity_id: "483", name: "Togo", continent: "AF", cq_zones: &[35], itu_zones: &[46], deleted: false },
    DxccEntity { entity_id: "488", name: "Walvis Bay", continent: "AF", cq_zones: &[38], itu_zones: &[57], deleted: true },
    DxccEntity { entity_id: "489", name: "Conway Reef", continent: "OC", cq_zones: &[32], itu_zones: &[56], deleted: false },
    DxccEntity { entity_id: "490", name: "Banaba I. (Ocean I.)", continent: "OC", cq_zones: &[31], itu_zones: &[65], deleted: false },
    DxccEntity { entity_id: "492", name: "Yemen", continent: "AS", cq_zones: &[21], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "493", name: "Penguin Is.", continent: "AF", cq_zones: &[38], itu_zones: &[57], deleted: true },
    DxccEntity { entity_id: "497", name: "Croatia", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "499", name: "Slovenia", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "501", name: "Bosnia-Herzegovina", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "502", name: "North Macedonia (Republic of)", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "503", name: "Czech Republic", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "504", name: "Slovak Republic", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "505", name: "Pratas I.", continent: "AS", cq_zones: &[24], itu_zones: &[44], deleted: false },
    DxccEntity { entity_id: "506", name: "Scarborough Reef", continent: "AS", cq_zones: &[27], itu_zones: &[50], deleted: false },
    DxccEntity { entity_id: "507", name: "Temotu Province", continent: "OC", cq_zones: &[32], itu_zones: &[51], deleted: false },
    DxccEntity { entity_id: "508", name: "Austral I.", continent: "OC", cq_zones: &[32], itu_zones: &[63], deleted: false },
    DxccEntity { entity_id: "509", name: "Marquesas Is.", continent: "OC", cq_zones: &[31], itu_zones: &[63], deleted: false },
    DxccEntity { entity_id: "510", name: "Palestine", continent: "AS", cq_zones: &[20], itu_zones: &[39], deleted: false },
    DxccEntity { entity_id: "511", name: "Timor-Leste", continent: "OC", cq_zones: &[28], itu_zones: &[54], deleted: false },
    DxccEntity { entity_id: "512", name: "Chesterfield Is.", continent: "OC", cq_zones: &[30], itu_zones: &[56], deleted: false },
    DxccEntity { entity_id: "513", name: "Ducie I.", continent: "OC", cq_zones: &[32], itu_zones: &[63], deleted: false },
    DxccEntity { entity_id: "514", name: "Montenegro", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
    DxccEntity { entity_id: "515", name: "Swains I.", continent: "OC", cq_zones: &[32], itu_zones: &[62], deleted: false },
    DxccEntity { entity_id: "516", name: "Saint Barthelemy", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "517", name: "Curacao", continent: "SA", cq_zones: &[9], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "518", name: "Sint Maarten", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "519", name: "Saba & St. Eustatius", continent: "NA", cq_zones: &[8], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "520", name: "Bonaire", continent: "SA", cq_zones: &[9], itu_zones: &[11], deleted: false },
    DxccEntity { entity_id: "521", name: "South Sudan (Republic of)", continent: "AF", cq_zones: &[34], itu_zones: &[48], deleted: false },
    DxccEntity { entity_id: "522", name: "Republic of Kosovo", continent: "EU", cq_zones: &[15], itu_zones: &[28], deleted: false },
];

/// Get entity by ID (ARRL 3-digit format: "001", "291", etc.)
pub fn get_entity_by_id(entity_id: &str) -> Option<&'static DxccEntity> {
    DXCC_ENTITIES.iter().find(|e| e.entity_id == entity_id)
}

/// Get entity by name (case-insensitive)
pub fn get_entity_by_name(name: &str) -> Option<&'static DxccEntity> {
    let name_lower = name.to_lowercase();
    DXCC_ENTITIES.iter().find(|e| e.name.to_lowercase() == name_lower)
}

/// Get all current (non-deleted) entities
pub fn get_current_entities() -> Vec<&'static DxccEntity> {
    DXCC_ENTITIES.iter().filter(|e| !e.deleted).collect()
}

/// Get count of current entities
pub fn get_current_entity_count() -> usize {
    DXCC_ENTITIES.iter().filter(|e| !e.deleted).count()
}
