//! Prefix to DXCC Entity mapping
//!
//! DO NOT EDIT THIS FILE DIRECTLY
//!
//! Generated from: src-tauri/resources/prefix_rules.json
//! Generator: scripts/generate_prefixes.py
//! Generated: 2026-01-15 20:14:08 UTC
//!
//! Statistics:
//!   Total rules: 806
//!   Entities covered: 339/340
//!   Coverage: 99.7%
//!
//! To update: modify prefix_rules.json and run:
//!   python scripts/generate_prefixes.py
//!
//! Source: ARRL DXCC list + ITU Radio Regulations + operator conventions
//! Authority: https://www.arrl.org/files/file/DXCC/Current_Deleted.txt

/// A prefix rule for matching callsigns to DXCC entities
#[derive(Debug, Clone)]
pub struct PrefixRule {
    /// The prefix pattern (e.g., "W", "VE", "JA")
    pub prefix: &'static str,
    /// The DXCC entity ID (ARRL 3-digit format: "001", "291", etc.)
    pub entity_id: &'static str,
    /// Optional: exact match only (for special calls)
    pub exact: bool,
    /// Priority for overlapping prefixes (higher = more specific)
    pub priority: u8,
}

/// Prefix rules generated from prefix_rules.json
/// Total: 806 rules covering 339 DXCC entities
pub const PREFIX_RULES: &[PrefixRule] = &[
    // === 1 ===
    PrefixRule { prefix: "1A", entity_id: "246", exact: false, priority: 30 }, // Sovereign Military Order of Malta

    // === 2 ===
    PrefixRule { prefix: "2E", entity_id: "223", exact: false, priority: 10 }, // United Kingdom of Great Britain
    PrefixRule { prefix: "2I", entity_id: "265", exact: false, priority: 30 }, // Northern Ireland
    PrefixRule { prefix: "2J", entity_id: "122", exact: false, priority: 30 }, // Jersey
    PrefixRule { prefix: "2M", entity_id: "279", exact: false, priority: 20 }, // Scotland
    PrefixRule { prefix: "2U", entity_id: "106", exact: false, priority: 30 }, // Guernsey
    PrefixRule { prefix: "2W", entity_id: "294", exact: false, priority: 20 }, // Wales

    // === 3 ===
    PrefixRule { prefix: "3A", entity_id: "260", exact: false, priority: 30 }, // Monaco
    PrefixRule { prefix: "3B6", entity_id: "004", exact: false, priority: 10 }, // Agalega & St. Brandon Is.
    PrefixRule { prefix: "3B7", entity_id: "004", exact: false, priority: 10 }, // Agalega & St. Brandon Is.
    PrefixRule { prefix: "3B8", entity_id: "165", exact: false, priority: 10 }, // Mauritius
    PrefixRule { prefix: "3B9", entity_id: "207", exact: false, priority: 10 }, // Rodrigues I.
    PrefixRule { prefix: "3C", entity_id: "049", exact: false, priority: 10 }, // Equatorial Guinea
    PrefixRule { prefix: "3C0", entity_id: "195", exact: false, priority: 30 }, // Annobon I.
    PrefixRule { prefix: "3D2", entity_id: "176", exact: false, priority: 10 }, // Fiji (Republic of)
    PrefixRule { prefix: "3D2/C", entity_id: "489", exact: false, priority: 30 }, // Conway Reef
    PrefixRule { prefix: "3D2/R", entity_id: "460", exact: false, priority: 30 }, // Rotuma I.
    PrefixRule { prefix: "3D2C", entity_id: "489", exact: false, priority: 60 }, // Conway Reef
    PrefixRule { prefix: "3D2R", entity_id: "460", exact: false, priority: 60 }, // Rotuma I.
    PrefixRule { prefix: "3DA", entity_id: "468", exact: false, priority: 10 }, // Kingdom of Eswatini
    PrefixRule { prefix: "3E", entity_id: "088", exact: false, priority: 20 }, // Panama
    PrefixRule { prefix: "3F", entity_id: "088", exact: false, priority: 20 }, // Panama
    PrefixRule { prefix: "3G", entity_id: "112", exact: false, priority: 20 }, // Chile
    PrefixRule { prefix: "3V", entity_id: "474", exact: false, priority: 10 }, // Tunisia
    PrefixRule { prefix: "3W", entity_id: "293", exact: false, priority: 10 }, // Viet Nam
    PrefixRule { prefix: "3X", entity_id: "107", exact: false, priority: 10 }, // Guinea
    PrefixRule { prefix: "3Y", entity_id: "199", exact: false, priority: 30 }, // Peter 1 I.
    PrefixRule { prefix: "3Y", entity_id: "024", exact: false, priority: 10 }, // Bouvet
    PrefixRule { prefix: "3Y0B", entity_id: "024", exact: false, priority: 60 }, // Bouvet
    PrefixRule { prefix: "3Y0P", entity_id: "199", exact: false, priority: 60 }, // Peter 1 I.
    PrefixRule { prefix: "3Z", entity_id: "503", exact: false, priority: 10 }, // Czech Republic

    // === 4 ===
    PrefixRule { prefix: "4A", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "4B", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "4C", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "4D", entity_id: "375", exact: false, priority: 30 }, // Philippines
    PrefixRule { prefix: "4E", entity_id: "375", exact: false, priority: 30 }, // Philippines
    PrefixRule { prefix: "4F", entity_id: "375", exact: false, priority: 30 }, // Philippines
    PrefixRule { prefix: "4G", entity_id: "375", exact: false, priority: 30 }, // Philippines
    PrefixRule { prefix: "4H", entity_id: "375", exact: false, priority: 30 }, // Philippines
    PrefixRule { prefix: "4I", entity_id: "387", exact: false, priority: 10 }, // Thailand
    PrefixRule { prefix: "4J", entity_id: "018", exact: false, priority: 10 }, // Azerbaijan
    PrefixRule { prefix: "4K", entity_id: "018", exact: false, priority: 10 }, // Azerbaijan
    PrefixRule { prefix: "4L", entity_id: "075", exact: false, priority: 10 }, // Georgia
    PrefixRule { prefix: "4M", entity_id: "148", exact: false, priority: 20 }, // Venezuela
    PrefixRule { prefix: "4O", entity_id: "514", exact: false, priority: 30 }, // Montenegro
    PrefixRule { prefix: "4P", entity_id: "315", exact: false, priority: 10 }, // Sri Lanka
    PrefixRule { prefix: "4Q", entity_id: "315", exact: false, priority: 10 }, // Sri Lanka
    PrefixRule { prefix: "4R", entity_id: "315", exact: false, priority: 10 }, // Sri Lanka
    PrefixRule { prefix: "4S", entity_id: "315", exact: false, priority: 10 }, // Sri Lanka
    PrefixRule { prefix: "4T", entity_id: "136", exact: false, priority: 20 }, // Peru
    PrefixRule { prefix: "4U_ITU", entity_id: "117", exact: false, priority: 70 }, // ITU HQ
    PrefixRule { prefix: "4U_UN", entity_id: "289", exact: false, priority: 60 }, // United Nations HQ
    PrefixRule { prefix: "4V", entity_id: "078", exact: false, priority: 20 }, // Haiti
    PrefixRule { prefix: "4W", entity_id: "511", exact: false, priority: 10 }, // Timor-Leste
    PrefixRule { prefix: "4X", entity_id: "336", exact: false, priority: 10 }, // Israel
    PrefixRule { prefix: "4Z", entity_id: "336", exact: false, priority: 10 }, // Israel

    // === 5 ===
    PrefixRule { prefix: "5A", entity_id: "436", exact: false, priority: 10 }, // Libya
    PrefixRule { prefix: "5B", entity_id: "215", exact: false, priority: 30 }, // Cyprus
    PrefixRule { prefix: "5C", entity_id: "446", exact: false, priority: 10 }, // Morocco (Kingdom of)
    PrefixRule { prefix: "5D", entity_id: "446", exact: false, priority: 10 }, // Morocco (Kingdom of)
    PrefixRule { prefix: "5E", entity_id: "446", exact: false, priority: 10 }, // Morocco (Kingdom of)
    PrefixRule { prefix: "5F", entity_id: "446", exact: false, priority: 10 }, // Morocco (Kingdom of)
    PrefixRule { prefix: "5G", entity_id: "446", exact: false, priority: 10 }, // Morocco (Kingdom of)
    PrefixRule { prefix: "5H", entity_id: "470", exact: false, priority: 10 }, // Tanzania (United Republic of)
    PrefixRule { prefix: "5I", entity_id: "470", exact: false, priority: 10 }, // Tanzania (United Republic of)
    PrefixRule { prefix: "5J", entity_id: "116", exact: false, priority: 20 }, // Colombia
    PrefixRule { prefix: "5K", entity_id: "116", exact: false, priority: 20 }, // Colombia
    PrefixRule { prefix: "5N", entity_id: "450", exact: false, priority: 10 }, // Nigeria
    PrefixRule { prefix: "5P", entity_id: "221", exact: false, priority: 30 }, // Denmark
    PrefixRule { prefix: "5Q", entity_id: "221", exact: false, priority: 30 }, // Denmark
    PrefixRule { prefix: "5R", entity_id: "438", exact: false, priority: 10 }, // Madagascar
    PrefixRule { prefix: "5T", entity_id: "444", exact: false, priority: 10 }, // Mauritania
    PrefixRule { prefix: "5U", entity_id: "187", exact: false, priority: 10 }, // Niger
    PrefixRule { prefix: "5V", entity_id: "483", exact: false, priority: 10 }, // Togo
    PrefixRule { prefix: "5W", entity_id: "190", exact: false, priority: 10 }, // Samoa
    PrefixRule { prefix: "5X", entity_id: "286", exact: false, priority: 10 }, // Uganda
    PrefixRule { prefix: "5Y", entity_id: "430", exact: false, priority: 10 }, // Kenya
    PrefixRule { prefix: "5Z", entity_id: "430", exact: false, priority: 10 }, // Kenya

    // === 6 ===
    PrefixRule { prefix: "6D", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "6E", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "6F", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "6G", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "6H", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "6I", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "6J", entity_id: "050", exact: false, priority: 10 }, // Mexico
    PrefixRule { prefix: "6K", entity_id: "137", exact: false, priority: 30 }, // Korea (Republic of)
    PrefixRule { prefix: "6L", entity_id: "137", exact: false, priority: 30 }, // Korea (Republic of)
    PrefixRule { prefix: "6M", entity_id: "137", exact: false, priority: 30 }, // Korea (Republic of)
    PrefixRule { prefix: "6N", entity_id: "137", exact: false, priority: 30 }, // Korea (Republic of)
    PrefixRule { prefix: "6N", entity_id: "321", exact: false, priority: 10 }, // Hong Kong
    PrefixRule { prefix: "6O", entity_id: "232", exact: false, priority: 10 }, // Somalia
    PrefixRule { prefix: "6V", entity_id: "456", exact: false, priority: 10 }, // Senegal
    PrefixRule { prefix: "6W", entity_id: "456", exact: false, priority: 10 }, // Senegal
    PrefixRule { prefix: "6Y", entity_id: "082", exact: false, priority: 20 }, // Jamaica

    // === 7 ===
    PrefixRule { prefix: "7J", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "7K", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "7L", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "7M", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "7N", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "7O", entity_id: "492", exact: false, priority: 10 }, // Yemen
    PrefixRule { prefix: "7P", entity_id: "432", exact: false, priority: 10 }, // Lesotho
    PrefixRule { prefix: "7Q", entity_id: "440", exact: false, priority: 10 }, // Malawi
    PrefixRule { prefix: "7R", entity_id: "400", exact: false, priority: 10 }, // Algeria (People's Dem Rep of)
    PrefixRule { prefix: "7S", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "7T", entity_id: "400", exact: false, priority: 10 }, // Algeria (People's Dem Rep of)
    PrefixRule { prefix: "7U", entity_id: "400", exact: false, priority: 10 }, // Algeria (People's Dem Rep of)
    PrefixRule { prefix: "7V", entity_id: "400", exact: false, priority: 10 }, // Algeria (People's Dem Rep of)
    PrefixRule { prefix: "7W", entity_id: "400", exact: false, priority: 10 }, // Algeria (People's Dem Rep of)
    PrefixRule { prefix: "7X", entity_id: "400", exact: false, priority: 10 }, // Algeria (People's Dem Rep of)
    PrefixRule { prefix: "7Y", entity_id: "400", exact: false, priority: 10 }, // Algeria (People's Dem Rep of)

    // === 8 ===
    PrefixRule { prefix: "8J", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "8K", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "8L", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "8M", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "8N", entity_id: "318", exact: false, priority: 10 }, // China
    PrefixRule { prefix: "8O", entity_id: "402", exact: false, priority: 10 }, // Botswana (Republic of)
    PrefixRule { prefix: "8P", entity_id: "062", exact: false, priority: 20 }, // Barbados
    PrefixRule { prefix: "8Q", entity_id: "159", exact: false, priority: 10 }, // Maldives
    PrefixRule { prefix: "8R", entity_id: "129", exact: false, priority: 20 }, // Guyana
    PrefixRule { prefix: "8S", entity_id: "284", exact: false, priority: 30 }, // Sweden

    // === 9 ===
    PrefixRule { prefix: "9A", entity_id: "497", exact: false, priority: 30 }, // Croatia
    PrefixRule { prefix: "9G", entity_id: "424", exact: false, priority: 10 }, // Ghana
    PrefixRule { prefix: "9H", entity_id: "257", exact: false, priority: 30 }, // Malta
    PrefixRule { prefix: "9I", entity_id: "482", exact: false, priority: 10 }, // Zambia
    PrefixRule { prefix: "9J", entity_id: "482", exact: false, priority: 10 }, // Zambia
    PrefixRule { prefix: "9K", entity_id: "348", exact: false, priority: 10 }, // Kuwait
    PrefixRule { prefix: "9L", entity_id: "458", exact: false, priority: 10 }, // Sierra Leone
    PrefixRule { prefix: "9M", entity_id: "299", exact: false, priority: 30 }, // West Malaysia
    PrefixRule { prefix: "9M2", entity_id: "299", exact: false, priority: 20 }, // West Malaysia
    PrefixRule { prefix: "9M4", entity_id: "299", exact: false, priority: 20 }, // West Malaysia
    PrefixRule { prefix: "9M6", entity_id: "046", exact: false, priority: 20 }, // East Malaysia
    PrefixRule { prefix: "9M8", entity_id: "046", exact: false, priority: 20 }, // East Malaysia
    PrefixRule { prefix: "9N", entity_id: "369", exact: false, priority: 10 }, // Nepal
    PrefixRule { prefix: "9O", entity_id: "414", exact: false, priority: 10 }, // Democratic Republic of the Congo
    PrefixRule { prefix: "9P", entity_id: "414", exact: false, priority: 10 }, // Democratic Republic of the Congo
    PrefixRule { prefix: "9Q", entity_id: "414", exact: false, priority: 10 }, // Democratic Republic of the Congo
    PrefixRule { prefix: "9R", entity_id: "414", exact: false, priority: 10 }, // Democratic Republic of the Congo
    PrefixRule { prefix: "9S", entity_id: "414", exact: false, priority: 10 }, // Democratic Republic of the Congo
    PrefixRule { prefix: "9T", entity_id: "414", exact: false, priority: 10 }, // Democratic Republic of the Congo
    PrefixRule { prefix: "9U", entity_id: "404", exact: false, priority: 10 }, // Burundi
    PrefixRule { prefix: "9V", entity_id: "381", exact: false, priority: 10 }, // Singapore (Republic of)
    PrefixRule { prefix: "9W", entity_id: "299", exact: false, priority: 30 }, // West Malaysia
    PrefixRule { prefix: "9X", entity_id: "454", exact: false, priority: 10 }, // Rwanda
    PrefixRule { prefix: "9Y", entity_id: "090", exact: false, priority: 20 }, // Trinidad & Tobago
    PrefixRule { prefix: "9Z", entity_id: "090", exact: false, priority: 20 }, // Trinidad & Tobago

    // === A ===
    PrefixRule { prefix: "A2", entity_id: "402", exact: false, priority: 10 }, // Botswana (Republic of)
    PrefixRule { prefix: "A3", entity_id: "160", exact: false, priority: 10 }, // Tonga
    PrefixRule { prefix: "A4", entity_id: "370", exact: false, priority: 10 }, // Oman
    PrefixRule { prefix: "A5", entity_id: "306", exact: false, priority: 10 }, // Bhutan
    PrefixRule { prefix: "A6", entity_id: "391", exact: false, priority: 10 }, // United Arab Emirates
    PrefixRule { prefix: "A7", entity_id: "376", exact: false, priority: 10 }, // Qatar
    PrefixRule { prefix: "A9", entity_id: "304", exact: false, priority: 10 }, // Bahrain
    PrefixRule { prefix: "AA", entity_id: "291", exact: false, priority: 30 }, // United States of America
    PrefixRule { prefix: "AB", entity_id: "291", exact: false, priority: 30 }, // United States of America
    PrefixRule { prefix: "AC", entity_id: "291", exact: false, priority: 30 }, // United States of America
    PrefixRule { prefix: "AD", entity_id: "291", exact: false, priority: 30 }, // United States of America
    PrefixRule { prefix: "AE", entity_id: "291", exact: false, priority: 30 }, // United States of America
    PrefixRule { prefix: "AF", entity_id: "291", exact: false, priority: 30 }, // United States of America
    PrefixRule { prefix: "AG", entity_id: "291", exact: false, priority: 30 }, // United States of America
    PrefixRule { prefix: "AH", entity_id: "291", exact: false, priority: 30 }, // United States of America
    PrefixRule { prefix: "AH0", entity_id: "166", exact: false, priority: 30 }, // Mariana Is.
    PrefixRule { prefix: "AH1", entity_id: "020", exact: false, priority: 30 }, // Baker & Howland Is.
    PrefixRule { prefix: "AH2", entity_id: "103", exact: false, priority: 30 }, // Guam
    PrefixRule { prefix: "AH3", entity_id: "123", exact: false, priority: 30 }, // Johnston I.
    PrefixRule { prefix: "AH4", entity_id: "174", exact: false, priority: 30 }, // Midway I.
    PrefixRule { prefix: "AH5", entity_id: "197", exact: false, priority: 30 }, // Palmyra & Jarvis Is.
    PrefixRule { prefix: "AH6", entity_id: "110", exact: false, priority: 30 }, // Hawaii
    PrefixRule { prefix: "AH7", entity_id: "110", exact: false, priority: 30 }, // Hawaii
    PrefixRule { prefix: "AH8", entity_id: "009", exact: false, priority: 30 }, // American Samoa
    PrefixRule { prefix: "AI", entity_id: "291", exact: false, priority: 30 }, // United States of America
    PrefixRule { prefix: "AJ", entity_id: "291", exact: false, priority: 30 }, // United States of America
    PrefixRule { prefix: "AK", entity_id: "291", exact: false, priority: 30 }, // United States of America
    PrefixRule { prefix: "AL", entity_id: "006", exact: false, priority: 30 }, // Alaska
    PrefixRule { prefix: "AP", entity_id: "372", exact: false, priority: 10 }, // Pakistan (Islamic Rep of)
    PrefixRule { prefix: "AS", entity_id: "372", exact: false, priority: 10 }, // Pakistan (Islamic Rep of)
    PrefixRule { prefix: "AX", entity_id: "150", exact: false, priority: 30 }, // Australia
    PrefixRule { prefix: "AY", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "AZ", entity_id: "108", exact: false, priority: 10 }, // Brazil

    // === B ===
    PrefixRule { prefix: "BS7", entity_id: "506", exact: false, priority: 40 }, // Scarborough Reef
    PrefixRule { prefix: "BV", entity_id: "386", exact: false, priority: 20 }, // Taiwan
    PrefixRule { prefix: "BV9P", entity_id: "505", exact: false, priority: 50 }, // Pratas I.
    PrefixRule { prefix: "BY", entity_id: "318", exact: false, priority: 30 }, // China

    // === C ===
    PrefixRule { prefix: "C2", entity_id: "157", exact: false, priority: 10 }, // Nauru
    PrefixRule { prefix: "C3", entity_id: "203", exact: false, priority: 30 }, // Andorra
    PrefixRule { prefix: "C4", entity_id: "215", exact: false, priority: 30 }, // Cyprus
    PrefixRule { prefix: "C5", entity_id: "422", exact: false, priority: 10 }, // Gambia (Republic of the)
    PrefixRule { prefix: "C6", entity_id: "060", exact: false, priority: 20 }, // Bahamas (Commonwealth of the)
    PrefixRule { prefix: "C8", entity_id: "181", exact: false, priority: 10 }, // Mozambique
    PrefixRule { prefix: "C9", entity_id: "181", exact: false, priority: 10 }, // Mozambique
    PrefixRule { prefix: "CA", entity_id: "112", exact: false, priority: 20 }, // Chile
    PrefixRule { prefix: "CB", entity_id: "112", exact: false, priority: 20 }, // Chile
    PrefixRule { prefix: "CC", entity_id: "112", exact: false, priority: 20 }, // Chile
    PrefixRule { prefix: "CD", entity_id: "112", exact: false, priority: 20 }, // Chile
    PrefixRule { prefix: "CE", entity_id: "112", exact: false, priority: 20 }, // Chile
    PrefixRule { prefix: "CE0", entity_id: "047", exact: false, priority: 30 }, // Easter I.
    PrefixRule { prefix: "CE0X", entity_id: "217", exact: false, priority: 40 }, // San Felix & San Ambrosio
    PrefixRule { prefix: "CE0Y", entity_id: "047", exact: false, priority: 40 }, // Easter I.
    PrefixRule { prefix: "CE0Z", entity_id: "125", exact: false, priority: 40 }, // Juan Fernandez Is.
    PrefixRule { prefix: "CE9", entity_id: "013", exact: false, priority: 40 }, // Antarctica
    PrefixRule { prefix: "CE9/KC4", entity_id: "013", exact: false, priority: 80 }, // Antarctica
    PrefixRule { prefix: "CL", entity_id: "070", exact: false, priority: 20 }, // Cuba
    PrefixRule { prefix: "CM", entity_id: "070", exact: false, priority: 20 }, // Cuba
    PrefixRule { prefix: "CN", entity_id: "446", exact: false, priority: 10 }, // Morocco (Kingdom of)
    PrefixRule { prefix: "CO", entity_id: "070", exact: false, priority: 20 }, // Cuba
    PrefixRule { prefix: "CP", entity_id: "104", exact: false, priority: 20 }, // Bolivia
    PrefixRule { prefix: "CQ", entity_id: "272", exact: false, priority: 30 }, // Portugal
    PrefixRule { prefix: "CR", entity_id: "272", exact: false, priority: 30 }, // Portugal
    PrefixRule { prefix: "CS", entity_id: "272", exact: false, priority: 30 }, // Portugal
    PrefixRule { prefix: "CT", entity_id: "272", exact: false, priority: 30 }, // Portugal
    PrefixRule { prefix: "CT3", entity_id: "256", exact: false, priority: 30 }, // Madeira Is.
    PrefixRule { prefix: "CU", entity_id: "149", exact: false, priority: 30 }, // Azores
    PrefixRule { prefix: "CU", entity_id: "272", exact: false, priority: 30 }, // Portugal
    PrefixRule { prefix: "CV", entity_id: "144", exact: false, priority: 20 }, // Uruguay
    PrefixRule { prefix: "CW", entity_id: "144", exact: false, priority: 20 }, // Uruguay
    PrefixRule { prefix: "CX", entity_id: "144", exact: false, priority: 20 }, // Uruguay
    PrefixRule { prefix: "CY0", entity_id: "211", exact: false, priority: 40 }, // Sable I.
    PrefixRule { prefix: "CY9", entity_id: "252", exact: false, priority: 40 }, // St. Paul I.

    // === D ===
    PrefixRule { prefix: "D2", entity_id: "401", exact: false, priority: 10 }, // Angola
    PrefixRule { prefix: "D3", entity_id: "401", exact: false, priority: 10 }, // Angola
    PrefixRule { prefix: "D4", entity_id: "409", exact: false, priority: 10 }, // Cabo Verde (Rep of)
    PrefixRule { prefix: "D6", entity_id: "411", exact: false, priority: 10 }, // Comoros
    PrefixRule { prefix: "DA", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DB", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DC", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DD", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DE", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DF", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DG", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DH", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DI", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DJ", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DK", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DL", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DM", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DN", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DO", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DP", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DP0", entity_id: "013", exact: false, priority: 40 }, // Antarctica
    PrefixRule { prefix: "DQ", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DR", entity_id: "230", exact: false, priority: 30 }, // Germany (Federal Rep of)
    PrefixRule { prefix: "DR", entity_id: "227", exact: false, priority: 10 }, // France
    PrefixRule { prefix: "DS", entity_id: "137", exact: false, priority: 30 }, // Republic of Korea
    PrefixRule { prefix: "DU", entity_id: "375", exact: false, priority: 30 }, // Philippines
    PrefixRule { prefix: "DV", entity_id: "375", exact: false, priority: 30 }, // Philippines
    PrefixRule { prefix: "DW", entity_id: "375", exact: false, priority: 30 }, // Philippines
    PrefixRule { prefix: "DX", entity_id: "375", exact: false, priority: 30 }, // Philippines
    PrefixRule { prefix: "DY", entity_id: "375", exact: false, priority: 30 }, // Philippines
    PrefixRule { prefix: "DZ", entity_id: "375", exact: false, priority: 30 }, // Philippines

    // === E ===
    PrefixRule { prefix: "E", entity_id: "124", exact: false, priority: 20 }, // Juan de Nova, Europa
    PrefixRule { prefix: "E2", entity_id: "324", exact: false, priority: 10 }, // India
    PrefixRule { prefix: "E3", entity_id: "051", exact: false, priority: 10 }, // Eritrea
    PrefixRule { prefix: "E4", entity_id: "510", exact: false, priority: 30 }, // Palestine
    PrefixRule { prefix: "E5", entity_id: "191", exact: false, priority: 10 }, // North Cook Is.
    PrefixRule { prefix: "E51", entity_id: "191", exact: false, priority: 50 }, // North Cook Is.
    PrefixRule { prefix: "E51", entity_id: "234", exact: false, priority: 30 }, // South Cook Is.
    PrefixRule { prefix: "E52", entity_id: "234", exact: false, priority: 50 }, // South Cook Is.
    PrefixRule { prefix: "E6", entity_id: "188", exact: false, priority: 10 }, // Niue
    PrefixRule { prefix: "E7", entity_id: "501", exact: false, priority: 30 }, // Bosnia-Herzegovina
    PrefixRule { prefix: "EA", entity_id: "281", exact: false, priority: 30 }, // Spain
    PrefixRule { prefix: "EA6", entity_id: "021", exact: false, priority: 30 }, // Balearic Is.
    PrefixRule { prefix: "EA8", entity_id: "029", exact: false, priority: 30 }, // Canary Is.
    PrefixRule { prefix: "EA9", entity_id: "032", exact: false, priority: 30 }, // Ceuta & Melilla
    PrefixRule { prefix: "EB", entity_id: "281", exact: false, priority: 30 }, // Spain
    PrefixRule { prefix: "EC", entity_id: "281", exact: false, priority: 30 }, // Spain
    PrefixRule { prefix: "ED", entity_id: "281", exact: false, priority: 30 }, // Spain
    PrefixRule { prefix: "EE", entity_id: "281", exact: false, priority: 30 }, // Spain
    PrefixRule { prefix: "EF", entity_id: "281", exact: false, priority: 30 }, // Spain
    PrefixRule { prefix: "EG", entity_id: "281", exact: false, priority: 30 }, // Spain
    PrefixRule { prefix: "EH", entity_id: "281", exact: false, priority: 30 }, // Spain
    PrefixRule { prefix: "EI", entity_id: "245", exact: false, priority: 30 }, // Ireland
    PrefixRule { prefix: "EJ", entity_id: "245", exact: false, priority: 30 }, // Ireland
    PrefixRule { prefix: "EJ", entity_id: "122", exact: false, priority: 10 }, // Jersey
    PrefixRule { prefix: "EK", entity_id: "014", exact: false, priority: 10 }, // Armenia
    PrefixRule { prefix: "EL", entity_id: "434", exact: false, priority: 10 }, // Liberia
    PrefixRule { prefix: "EM", entity_id: "288", exact: false, priority: 30 }, // Ukraine
    PrefixRule { prefix: "EN", entity_id: "288", exact: false, priority: 30 }, // Ukraine
    PrefixRule { prefix: "EO", entity_id: "288", exact: false, priority: 10 }, // Ukraine
    PrefixRule { prefix: "EP", entity_id: "330", exact: false, priority: 10 }, // Iran (Islamic Repub of)
    PrefixRule { prefix: "EQ", entity_id: "330", exact: false, priority: 10 }, // Iran (Islamic Repub of)
    PrefixRule { prefix: "ER", entity_id: "179", exact: false, priority: 30 }, // Moldova (Republic of)
    PrefixRule { prefix: "ES", entity_id: "052", exact: false, priority: 10 }, // Estonia
    PrefixRule { prefix: "ET", entity_id: "053", exact: false, priority: 10 }, // Ethiopia
    PrefixRule { prefix: "EU", entity_id: "027", exact: false, priority: 30 }, // Belarus (Republic of)
    PrefixRule { prefix: "EV", entity_id: "027", exact: false, priority: 30 }, // Belarus (Republic of)
    PrefixRule { prefix: "EW", entity_id: "027", exact: false, priority: 30 }, // Belarus (Republic of)
    PrefixRule { prefix: "EX", entity_id: "135", exact: false, priority: 10 }, // Kyrgyz Republic
    PrefixRule { prefix: "EY", entity_id: "262", exact: false, priority: 10 }, // Tajikistan
    PrefixRule { prefix: "EZ", entity_id: "280", exact: false, priority: 10 }, // Turkmenistan

    // === F ===
    PrefixRule { prefix: "F", entity_id: "248", exact: false, priority: 10 }, // Italy
    PrefixRule { prefix: "FG", entity_id: "079", exact: false, priority: 30 }, // Guadeloupe
    PrefixRule { prefix: "FH", entity_id: "169", exact: false, priority: 10 }, // Mayotte
    PrefixRule { prefix: "FJ", entity_id: "214", exact: false, priority: 30 }, // Corsica
    PrefixRule { prefix: "FJ", entity_id: "516", exact: false, priority: 30 }, // Saint Barthelemy
    PrefixRule { prefix: "FK", entity_id: "162", exact: false, priority: 10 }, // New Caledonia
    PrefixRule { prefix: "FK0C", entity_id: "512", exact: false, priority: 60 }, // Chesterfield Is.
    PrefixRule { prefix: "FM", entity_id: "084", exact: false, priority: 30 }, // Martinique
    PrefixRule { prefix: "FO", entity_id: "036", exact: false, priority: 30 }, // Clipperton I.
    PrefixRule { prefix: "FO", entity_id: "508", exact: false, priority: 30 }, // Austral I.
    PrefixRule { prefix: "FO", entity_id: "509", exact: false, priority: 30 }, // Marquesas Is.
    PrefixRule { prefix: "FO", entity_id: "175", exact: false, priority: 10 }, // French Polynesia
    PrefixRule { prefix: "FO0A", entity_id: "508", exact: false, priority: 60 }, // Austral I.
    PrefixRule { prefix: "FO0C", entity_id: "036", exact: false, priority: 60 }, // Clipperton I.
    PrefixRule { prefix: "FO0M", entity_id: "509", exact: false, priority: 60 }, // Marquesas Is.
    PrefixRule { prefix: "FP", entity_id: "277", exact: false, priority: 30 }, // St. Pierre & Miquelon
    PrefixRule { prefix: "FR", entity_id: "453", exact: false, priority: 10 }, // Reunion I.
    PrefixRule { prefix: "FS", entity_id: "213", exact: false, priority: 30 }, // Saint Martin
    PrefixRule { prefix: "FT/G", entity_id: "099", exact: false, priority: 50 }, // Glorioso Is.
    PrefixRule { prefix: "FT/J", entity_id: "124", exact: false, priority: 50 }, // Juan de Nova, Europa
    PrefixRule { prefix: "FT/T", entity_id: "276", exact: false, priority: 50 }, // Tromelin I.
    PrefixRule { prefix: "FT/W", entity_id: "041", exact: false, priority: 50 }, // Crozet I.
    PrefixRule { prefix: "FT/X", entity_id: "131", exact: false, priority: 50 }, // Kerguelen Is.
    PrefixRule { prefix: "FT/Z", entity_id: "010", exact: false, priority: 50 }, // Amsterdam & St. Paul Is.
    PrefixRule { prefix: "FT0G", entity_id: "099", exact: false, priority: 50 }, // Glorioso Is.
    PrefixRule { prefix: "FT0J", entity_id: "124", exact: false, priority: 50 }, // Juan de Nova, Europa
    PrefixRule { prefix: "FT0T", entity_id: "276", exact: false, priority: 50 }, // Tromelin I.
    PrefixRule { prefix: "FT0W", entity_id: "041", exact: false, priority: 50 }, // Crozet I.
    PrefixRule { prefix: "FT0X", entity_id: "131", exact: false, priority: 50 }, // Kerguelen Is.
    PrefixRule { prefix: "FT0Z", entity_id: "010", exact: false, priority: 50 }, // Amsterdam & St. Paul Is.
    PrefixRule { prefix: "FW", entity_id: "298", exact: false, priority: 10 }, // Wallis & Futuna Is.
    PrefixRule { prefix: "FY", entity_id: "063", exact: false, priority: 30 }, // French Guiana

    // === G ===
    PrefixRule { prefix: "G", entity_id: "223", exact: false, priority: 10 }, // United Kingdom of Great Britain
    PrefixRule { prefix: "GD", entity_id: "114", exact: false, priority: 20 }, // Isle of Man
    PrefixRule { prefix: "GI", entity_id: "265", exact: false, priority: 20 }, // Northern Ireland
    PrefixRule { prefix: "GJ", entity_id: "122", exact: false, priority: 20 }, // Jersey
    PrefixRule { prefix: "GM", entity_id: "279", exact: false, priority: 20 }, // Scotland
    PrefixRule { prefix: "GU", entity_id: "106", exact: false, priority: 20 }, // Guernsey
    PrefixRule { prefix: "GW", entity_id: "294", exact: false, priority: 20 }, // Wales

    // === H ===
    PrefixRule { prefix: "H3", entity_id: "088", exact: false, priority: 20 }, // Panama
    PrefixRule { prefix: "H4", entity_id: "185", exact: false, priority: 10 }, // Solomon Is.
    PrefixRule { prefix: "H40", entity_id: "507", exact: false, priority: 30 }, // Temotu Province
    PrefixRule { prefix: "H6", entity_id: "086", exact: false, priority: 20 }, // Nicaragua
    PrefixRule { prefix: "H7", entity_id: "086", exact: false, priority: 20 }, // Nicaragua
    PrefixRule { prefix: "H8", entity_id: "088", exact: false, priority: 20 }, // Panama
    PrefixRule { prefix: "H9", entity_id: "088", exact: false, priority: 20 }, // Panama
    PrefixRule { prefix: "HA", entity_id: "239", exact: false, priority: 30 }, // Hungary
    PrefixRule { prefix: "HB", entity_id: "287", exact: false, priority: 30 }, // Switzerland
    PrefixRule { prefix: "HB0", entity_id: "251", exact: false, priority: 30 }, // Liechtenstein
    PrefixRule { prefix: "HC", entity_id: "120", exact: false, priority: 20 }, // Ecuador
    PrefixRule { prefix: "HC8", entity_id: "071", exact: false, priority: 30 }, // Galapagos Is.
    PrefixRule { prefix: "HD", entity_id: "120", exact: false, priority: 20 }, // Ecuador
    PrefixRule { prefix: "HD8", entity_id: "071", exact: false, priority: 30 }, // Galapagos Is.
    PrefixRule { prefix: "HE", entity_id: "287", exact: false, priority: 30 }, // Switzerland
    PrefixRule { prefix: "HF", entity_id: "269", exact: false, priority: 30 }, // Poland
    PrefixRule { prefix: "HG", entity_id: "275", exact: false, priority: 10 }, // Romania
    PrefixRule { prefix: "HH", entity_id: "078", exact: false, priority: 20 }, // Haiti
    PrefixRule { prefix: "HI", entity_id: "072", exact: false, priority: 20 }, // Dominican Republic
    PrefixRule { prefix: "HJ", entity_id: "116", exact: false, priority: 20 }, // Colombia
    PrefixRule { prefix: "HK", entity_id: "116", exact: false, priority: 20 }, // Colombia
    PrefixRule { prefix: "HK0", entity_id: "216", exact: false, priority: 30 }, // San Andres & Providencia
    PrefixRule { prefix: "HK0M", entity_id: "161", exact: false, priority: 40 }, // Malpelo I.
    PrefixRule { prefix: "HL", entity_id: "137", exact: false, priority: 30 }, // Korea (Republic of)
    PrefixRule { prefix: "HO", entity_id: "088", exact: false, priority: 20 }, // Panama
    PrefixRule { prefix: "HP", entity_id: "088", exact: false, priority: 20 }, // Panama
    PrefixRule { prefix: "HQ", entity_id: "080", exact: false, priority: 20 }, // Honduras
    PrefixRule { prefix: "HR", entity_id: "080", exact: false, priority: 20 }, // Honduras
    PrefixRule { prefix: "HS", entity_id: "387", exact: false, priority: 30 }, // Thailand
    PrefixRule { prefix: "HT", entity_id: "086", exact: false, priority: 20 }, // Nicaragua
    PrefixRule { prefix: "HU", entity_id: "074", exact: false, priority: 20 }, // El Salvador
    PrefixRule { prefix: "HV", entity_id: "295", exact: false, priority: 30 }, // Vatican
    PrefixRule { prefix: "HZ", entity_id: "378", exact: false, priority: 10 }, // Saudi Arabia

    // === I ===
    PrefixRule { prefix: "I", entity_id: "281", exact: false, priority: 10 }, // Spain
    PrefixRule { prefix: "IK", entity_id: "248", exact: false, priority: 30 }, // Italy
    PrefixRule { prefix: "IM0", entity_id: "225", exact: false, priority: 40 }, // Sardinia
    PrefixRule { prefix: "IS0", entity_id: "225", exact: false, priority: 40 }, // Sardinia
    PrefixRule { prefix: "IZ", entity_id: "248", exact: false, priority: 30 }, // Italy

    // === J ===
    PrefixRule { prefix: "J2", entity_id: "382", exact: false, priority: 10 }, // Djibouti
    PrefixRule { prefix: "J3", entity_id: "077", exact: false, priority: 20 }, // Grenada
    PrefixRule { prefix: "J4", entity_id: "236", exact: false, priority: 30 }, // Greece
    PrefixRule { prefix: "J5", entity_id: "109", exact: false, priority: 10 }, // Guinea-Bissau
    PrefixRule { prefix: "J6", entity_id: "097", exact: false, priority: 20 }, // St. Lucia
    PrefixRule { prefix: "J7", entity_id: "095", exact: false, priority: 20 }, // Dominica
    PrefixRule { prefix: "J8", entity_id: "098", exact: false, priority: 20 }, // St. Vincent
    PrefixRule { prefix: "JA", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JB", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JC", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JD", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JD1", entity_id: "177", exact: false, priority: 30 }, // Minami Torishima
    PrefixRule { prefix: "JD1/O", entity_id: "192", exact: false, priority: 40 }, // Ogasawara
    PrefixRule { prefix: "JD1M", entity_id: "177", exact: false, priority: 60 }, // Minami Torishima
    PrefixRule { prefix: "JD1O", entity_id: "192", exact: false, priority: 60 }, // Ogasawara
    PrefixRule { prefix: "JE", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JF", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JG", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JH", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JI", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JJ", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JK", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JL", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JM", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JN", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JO", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JP", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JQ", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JR", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JS", entity_id: "339", exact: false, priority: 30 }, // Japan
    PrefixRule { prefix: "JT", entity_id: "363", exact: false, priority: 10 }, // Mongolia
    PrefixRule { prefix: "JU", entity_id: "363", exact: false, priority: 10 }, // Mongolia
    PrefixRule { prefix: "JV", entity_id: "363", exact: false, priority: 10 }, // Mongolia
    PrefixRule { prefix: "JW", entity_id: "259", exact: false, priority: 10 }, // Svalbard
    PrefixRule { prefix: "JX", entity_id: "118", exact: false, priority: 10 }, // Jan Mayen
    PrefixRule { prefix: "JY", entity_id: "342", exact: false, priority: 10 }, // Jordan

    // === K ===
    PrefixRule { prefix: "K", entity_id: "291", exact: false, priority: 20 }, // United States of America
    PrefixRule { prefix: "KC4", entity_id: "013", exact: false, priority: 40 }, // Antarctica
    PrefixRule { prefix: "KC6", entity_id: "022", exact: false, priority: 40 }, // Palau
    PrefixRule { prefix: "KG4", entity_id: "291", exact: false, priority: 30 }, // USA (KG4 - see grid_overrides_dxcc fo...
    PrefixRule { prefix: "KH0", entity_id: "166", exact: false, priority: 40 }, // Mariana Is.
    PrefixRule { prefix: "KH1", entity_id: "020", exact: false, priority: 40 }, // Baker & Howland Is.
    PrefixRule { prefix: "KH2", entity_id: "103", exact: false, priority: 40 }, // Guam
    PrefixRule { prefix: "KH3", entity_id: "123", exact: false, priority: 40 }, // Johnston I.
    PrefixRule { prefix: "KH4", entity_id: "174", exact: false, priority: 40 }, // Midway I.
    PrefixRule { prefix: "KH5", entity_id: "197", exact: false, priority: 40 }, // Palmyra & Jarvis Is.
    PrefixRule { prefix: "KH6", entity_id: "110", exact: false, priority: 30 }, // Hawaii
    PrefixRule { prefix: "KH7", entity_id: "110", exact: false, priority: 40 }, // Hawaii
    PrefixRule { prefix: "KH7K", entity_id: "138", exact: false, priority: 50 }, // Kure I.
    PrefixRule { prefix: "KH8", entity_id: "515", exact: false, priority: 40 }, // Swains I.
    PrefixRule { prefix: "KH8S", entity_id: "515", exact: false, priority: 60 }, // Swains I.
    PrefixRule { prefix: "KH9", entity_id: "297", exact: false, priority: 40 }, // Wake I.
    PrefixRule { prefix: "KL", entity_id: "006", exact: false, priority: 30 }, // Alaska
    PrefixRule { prefix: "KL7", entity_id: "006", exact: false, priority: 40 }, // Alaska
    PrefixRule { prefix: "KP1", entity_id: "182", exact: false, priority: 30 }, // Navassa I.
    PrefixRule { prefix: "KP2", entity_id: "285", exact: false, priority: 30 }, // Virgin Is.
    PrefixRule { prefix: "KP3", entity_id: "202", exact: false, priority: 30 }, // Puerto Rico
    PrefixRule { prefix: "KP4", entity_id: "202", exact: false, priority: 30 }, // Puerto Rico
    PrefixRule { prefix: "KP5", entity_id: "043", exact: false, priority: 40 }, // Desecheo I.
    PrefixRule { prefix: "KX6", entity_id: "168", exact: false, priority: 40 }, // Marshall Is.

    // === L ===
    PrefixRule { prefix: "L2", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "L3", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "L4", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "L5", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "L6", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "L7", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "L8", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "L9", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "LA", entity_id: "266", exact: false, priority: 10 }, // Norway
    PrefixRule { prefix: "LB", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LC", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LD", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LE", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LF", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LG", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LH", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LI", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LJ", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LK", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LL", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LM", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LN", entity_id: "266", exact: false, priority: 30 }, // Norway
    PrefixRule { prefix: "LO", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "LP", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "LQ", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "LR", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "LS", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "LT", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "LU", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "LV", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "LW", entity_id: "100", exact: false, priority: 30 }, // Argentina
    PrefixRule { prefix: "LX", entity_id: "254", exact: false, priority: 30 }, // Luxembourg
    PrefixRule { prefix: "LY", entity_id: "146", exact: false, priority: 10 }, // Lithuania
    PrefixRule { prefix: "LZ", entity_id: "236", exact: false, priority: 10 }, // Greece

    // === M ===
    PrefixRule { prefix: "M", entity_id: "223", exact: false, priority: 10 }, // United Kingdom of Great Britain
    PrefixRule { prefix: "MD", entity_id: "114", exact: false, priority: 20 }, // Isle of Man
    PrefixRule { prefix: "MI", entity_id: "265", exact: false, priority: 20 }, // Northern Ireland
    PrefixRule { prefix: "MJ", entity_id: "122", exact: false, priority: 20 }, // Jersey
    PrefixRule { prefix: "MM", entity_id: "279", exact: false, priority: 20 }, // Scotland
    PrefixRule { prefix: "MU", entity_id: "106", exact: false, priority: 20 }, // Guernsey
    PrefixRule { prefix: "MW", entity_id: "294", exact: false, priority: 20 }, // Wales

    // === N ===
    PrefixRule { prefix: "N", entity_id: "291", exact: false, priority: 20 }, // United States of America
    PrefixRule { prefix: "NH6", entity_id: "110", exact: false, priority: 30 }, // Hawaii
    PrefixRule { prefix: "NL", entity_id: "006", exact: false, priority: 30 }, // Alaska
    PrefixRule { prefix: "NL7", entity_id: "006", exact: false, priority: 40 }, // Alaska
    PrefixRule { prefix: "NP2", entity_id: "285", exact: false, priority: 40 }, // US Virgin Is.
    PrefixRule { prefix: "NP3", entity_id: "202", exact: false, priority: 30 }, // Puerto Rico
    PrefixRule { prefix: "NP4", entity_id: "202", exact: false, priority: 30 }, // Puerto Rico

    // === O ===
    PrefixRule { prefix: "OA", entity_id: "136", exact: false, priority: 20 }, // Peru
    PrefixRule { prefix: "OB", entity_id: "136", exact: false, priority: 20 }, // Peru
    PrefixRule { prefix: "OC", entity_id: "136", exact: false, priority: 20 }, // Peru
    PrefixRule { prefix: "OD", entity_id: "354", exact: false, priority: 10 }, // Lebanon
    PrefixRule { prefix: "OE", entity_id: "206", exact: false, priority: 30 }, // Austria
    PrefixRule { prefix: "OE", entity_id: "269", exact: false, priority: 10 }, // Poland
    PrefixRule { prefix: "OF", entity_id: "224", exact: false, priority: 30 }, // Finland
    PrefixRule { prefix: "OG", entity_id: "224", exact: false, priority: 30 }, // Finland
    PrefixRule { prefix: "OH", entity_id: "224", exact: false, priority: 10 }, // Finland
    PrefixRule { prefix: "OH0", entity_id: "005", exact: false, priority: 30 }, // Aland Is.
    PrefixRule { prefix: "OI", entity_id: "224", exact: false, priority: 30 }, // Finland
    PrefixRule { prefix: "OJ", entity_id: "224", exact: false, priority: 30 }, // Finland
    PrefixRule { prefix: "OJ0", entity_id: "167", exact: false, priority: 40 }, // Market Reef
    PrefixRule { prefix: "OK", entity_id: "503", exact: false, priority: 30 }, // Czech Republic
    PrefixRule { prefix: "OL", entity_id: "503", exact: false, priority: 10 }, // Czech Republic
    PrefixRule { prefix: "OM", entity_id: "504", exact: false, priority: 30 }, // Slovak Republic
    PrefixRule { prefix: "OM", entity_id: "239", exact: false, priority: 10 }, // Hungary
    PrefixRule { prefix: "ON", entity_id: "209", exact: false, priority: 30 }, // Belgium
    PrefixRule { prefix: "OO", entity_id: "209", exact: false, priority: 30 }, // Belgium
    PrefixRule { prefix: "OP", entity_id: "209", exact: false, priority: 30 }, // Belgium
    PrefixRule { prefix: "OQ", entity_id: "209", exact: false, priority: 30 }, // Belgium
    PrefixRule { prefix: "OR", entity_id: "209", exact: false, priority: 30 }, // Belgium
    PrefixRule { prefix: "OS", entity_id: "209", exact: false, priority: 30 }, // Belgium
    PrefixRule { prefix: "OT", entity_id: "287", exact: false, priority: 10 }, // Switzerland
    PrefixRule { prefix: "OU", entity_id: "221", exact: false, priority: 30 }, // Denmark
    PrefixRule { prefix: "OV", entity_id: "221", exact: false, priority: 30 }, // Denmark
    PrefixRule { prefix: "OW", entity_id: "221", exact: false, priority: 30 }, // Denmark
    PrefixRule { prefix: "OX", entity_id: "237", exact: false, priority: 10 }, // Greenland
    PrefixRule { prefix: "OY", entity_id: "222", exact: false, priority: 10 }, // Faroe Is.
    PrefixRule { prefix: "OZ", entity_id: "221", exact: false, priority: 10 }, // Denmark

    // === P ===
    PrefixRule { prefix: "P2", entity_id: "163", exact: false, priority: 10 }, // Papua New Guinea
    PrefixRule { prefix: "P3", entity_id: "215", exact: false, priority: 30 }, // Cyprus
    PrefixRule { prefix: "P4", entity_id: "091", exact: false, priority: 20 }, // Aruba
    PrefixRule { prefix: "P5", entity_id: "344", exact: false, priority: 10 }, // Democratic People's Rep. of Korea
    PrefixRule { prefix: "PA", entity_id: "263", exact: false, priority: 30 }, // Netherlands
    PrefixRule { prefix: "PB", entity_id: "263", exact: false, priority: 30 }, // Netherlands
    PrefixRule { prefix: "PC", entity_id: "263", exact: false, priority: 30 }, // Netherlands
    PrefixRule { prefix: "PD", entity_id: "263", exact: false, priority: 30 }, // Netherlands
    PrefixRule { prefix: "PE", entity_id: "263", exact: false, priority: 30 }, // Netherlands
    PrefixRule { prefix: "PF", entity_id: "263", exact: false, priority: 30 }, // Netherlands
    PrefixRule { prefix: "PG", entity_id: "263", exact: false, priority: 30 }, // Netherlands
    PrefixRule { prefix: "PH", entity_id: "263", exact: false, priority: 30 }, // Netherlands
    PrefixRule { prefix: "PI", entity_id: "263", exact: false, priority: 30 }, // Netherlands
    PrefixRule { prefix: "PI", entity_id: "209", exact: false, priority: 10 }, // Belgium
    PrefixRule { prefix: "PJ2", entity_id: "517", exact: false, priority: 30 }, // Curacao
    PrefixRule { prefix: "PJ4", entity_id: "520", exact: false, priority: 30 }, // Bonaire
    PrefixRule { prefix: "PJ5", entity_id: "519", exact: false, priority: 30 }, // Saba & St. Eustatius
    PrefixRule { prefix: "PJ6", entity_id: "519", exact: false, priority: 30 }, // Saba & St. Eustatius
    PrefixRule { prefix: "PJ7", entity_id: "518", exact: false, priority: 30 }, // Sint Maarten
    PrefixRule { prefix: "PP", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "PP0-PY0F", entity_id: "056", exact: false, priority: 90 }, // Fernando de Noronha
    PrefixRule { prefix: "PP0-PY0S", entity_id: "253", exact: false, priority: 90 }, // St. Peter & St. Paul Rocks
    PrefixRule { prefix: "PP0-PY0T", entity_id: "273", exact: false, priority: 90 }, // Trindade & Martim Vaz Is.
    PrefixRule { prefix: "PQ", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "PR", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "PS", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "PT", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "PU", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "PV", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "PW", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "PX", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "PY", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "PY0F", entity_id: "056", exact: false, priority: 50 }, // Fernando de Noronha
    PrefixRule { prefix: "PY0S", entity_id: "253", exact: false, priority: 50 }, // St. Peter & St. Paul Rocks
    PrefixRule { prefix: "PY0T", entity_id: "273", exact: false, priority: 50 }, // Trindade & Martim Vaz Is.
    PrefixRule { prefix: "PZ", entity_id: "140", exact: false, priority: 20 }, // Suriname

    // === R ===
    PrefixRule { prefix: "R", entity_id: "054", exact: false, priority: 10 }, // European Russia
    PrefixRule { prefix: "R1/F", entity_id: "061", exact: false, priority: 50 }, // Franz Josef Land
    PrefixRule { prefix: "R1FJ", entity_id: "061", exact: false, priority: 50 }, // Franz Josef Land
    PrefixRule { prefix: "R9", entity_id: "288", exact: false, priority: 20 }, // Ukraine
    PrefixRule { prefix: "RA", entity_id: "054", exact: false, priority: 30 }, // European Russia
    PrefixRule { prefix: "RA2", entity_id: "126", exact: false, priority: 40 }, // Kaliningrad
    PrefixRule { prefix: "RI1", entity_id: "013", exact: false, priority: 40 }, // Antarctica
    PrefixRule { prefix: "RV", entity_id: "054", exact: false, priority: 30 }, // European Russia
    PrefixRule { prefix: "RW", entity_id: "054", exact: false, priority: 30 }, // European Russia
    PrefixRule { prefix: "RX", entity_id: "054", exact: false, priority: 30 }, // European Russia
    PrefixRule { prefix: "RZ", entity_id: "054", exact: false, priority: 30 }, // European Russia

    // === S ===
    PrefixRule { prefix: "S0", entity_id: "302", exact: false, priority: 10 }, // Western Sahara
    PrefixRule { prefix: "S2", entity_id: "305", exact: false, priority: 10 }, // Bangladesh
    PrefixRule { prefix: "S5", entity_id: "499", exact: false, priority: 30 }, // Slovenia
    PrefixRule { prefix: "S7", entity_id: "379", exact: false, priority: 10 }, // Seychelles
    PrefixRule { prefix: "S9", entity_id: "219", exact: false, priority: 10 }, // Sao Tome & Principe
    PrefixRule { prefix: "SA", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SB", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SC", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SD", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SE", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SF", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SG", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SH", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SI", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SJ", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SK", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SL", entity_id: "284", exact: false, priority: 30 }, // Sweden
    PrefixRule { prefix: "SM", entity_id: "284", exact: false, priority: 10 }, // Sweden
    PrefixRule { prefix: "SN", entity_id: "269", exact: false, priority: 30 }, // Poland
    PrefixRule { prefix: "SO", entity_id: "269", exact: false, priority: 30 }, // Poland
    PrefixRule { prefix: "SP", entity_id: "269", exact: false, priority: 30 }, // Poland
    PrefixRule { prefix: "SQ", entity_id: "269", exact: false, priority: 30 }, // Poland
    PrefixRule { prefix: "SR", entity_id: "269", exact: false, priority: 30 }, // Poland
    PrefixRule { prefix: "ST", entity_id: "466", exact: false, priority: 10 }, // Sudan
    PrefixRule { prefix: "SU", entity_id: "478", exact: false, priority: 10 }, // Egypt
    PrefixRule { prefix: "SV", entity_id: "236", exact: false, priority: 30 }, // Greece
    PrefixRule { prefix: "SV/A", entity_id: "180", exact: false, priority: 50 }, // Mount Athos
    PrefixRule { prefix: "SV5", entity_id: "045", exact: false, priority: 30 }, // Dodecanese
    PrefixRule { prefix: "SV9", entity_id: "040", exact: false, priority: 30 }, // Crete
    PrefixRule { prefix: "SW", entity_id: "236", exact: false, priority: 30 }, // Greece
    PrefixRule { prefix: "SX", entity_id: "236", exact: false, priority: 30 }, // Greece
    PrefixRule { prefix: "SY", entity_id: "236", exact: false, priority: 30 }, // Greece
    PrefixRule { prefix: "SZ", entity_id: "236", exact: false, priority: 30 }, // Greece

    // === T ===
    PrefixRule { prefix: "T2", entity_id: "282", exact: false, priority: 10 }, // Tuvalu
    PrefixRule { prefix: "T3", entity_id: "301", exact: false, priority: 30 }, // Kiribati
    PrefixRule { prefix: "T30", entity_id: "301", exact: false, priority: 20 }, // W. Kiribati (Gilbert Is. )
    PrefixRule { prefix: "T31", entity_id: "031", exact: false, priority: 20 }, // C. Kiribati (British Phoenix Is.)
    PrefixRule { prefix: "T32", entity_id: "048", exact: false, priority: 20 }, // E. Kiribati (Line Is.)
    PrefixRule { prefix: "T33", entity_id: "490", exact: false, priority: 20 }, // Banaba I. (Ocean I.)
    PrefixRule { prefix: "T4", entity_id: "070", exact: false, priority: 20 }, // Cuba
    PrefixRule { prefix: "T5", entity_id: "232", exact: false, priority: 10 }, // Somalia
    PrefixRule { prefix: "T6", entity_id: "003", exact: false, priority: 10 }, // Afghanistan
    PrefixRule { prefix: "T7", entity_id: "278", exact: false, priority: 30 }, // San Marino
    PrefixRule { prefix: "T8", entity_id: "022", exact: false, priority: 10 }, // Palau
    PrefixRule { prefix: "TA", entity_id: "390", exact: false, priority: 10 }, // Republic of Turkiye
    PrefixRule { prefix: "TB", entity_id: "390", exact: false, priority: 10 }, // Republic of Turkiye
    PrefixRule { prefix: "TC", entity_id: "390", exact: false, priority: 10 }, // Republic of Turkiye
    PrefixRule { prefix: "TD", entity_id: "076", exact: false, priority: 20 }, // Guatemala
    PrefixRule { prefix: "TE", entity_id: "308", exact: false, priority: 20 }, // Costa Rica
    PrefixRule { prefix: "TF", entity_id: "242", exact: false, priority: 10 }, // Iceland
    PrefixRule { prefix: "TG", entity_id: "076", exact: false, priority: 20 }, // Guatemala
    PrefixRule { prefix: "TI", entity_id: "308", exact: false, priority: 20 }, // Costa Rica
    PrefixRule { prefix: "TI9", entity_id: "037", exact: false, priority: 30 }, // Cocos I.
    PrefixRule { prefix: "TJ", entity_id: "406", exact: false, priority: 10 }, // Cameroon
    PrefixRule { prefix: "TL", entity_id: "408", exact: false, priority: 10 }, // Central Africa
    PrefixRule { prefix: "TM", entity_id: "227", exact: false, priority: 30 }, // France
    PrefixRule { prefix: "TN", entity_id: "412", exact: false, priority: 10 }, // Republic of the Congo
    PrefixRule { prefix: "TO", entity_id: "099", exact: false, priority: 30 }, // Glorioso Is.
    PrefixRule { prefix: "TO", entity_id: "124", exact: false, priority: 30 }, // Juan de Nova, Europa
    PrefixRule { prefix: "TO", entity_id: "276", exact: false, priority: 30 }, // Tromelin I.
    PrefixRule { prefix: "TO", entity_id: "508", exact: false, priority: 30 }, // Austral I.
    PrefixRule { prefix: "TO", entity_id: "516", exact: false, priority: 30 }, // Saint Barthelemy
    PrefixRule { prefix: "TO1", entity_id: "079", exact: false, priority: 50 }, // Guadeloupe
    PrefixRule { prefix: "TO2", entity_id: "084", exact: false, priority: 50 }, // Martinique
    PrefixRule { prefix: "TO4", entity_id: "453", exact: false, priority: 50 }, // Reunion I.
    PrefixRule { prefix: "TO5", entity_id: "099", exact: false, priority: 50 }, // Glorioso Is.
    PrefixRule { prefix: "TO7", entity_id: "169", exact: false, priority: 50 }, // Mayotte
    PrefixRule { prefix: "TR", entity_id: "420", exact: false, priority: 10 }, // Gabon
    PrefixRule { prefix: "TS", entity_id: "474", exact: false, priority: 30 }, // Tunisia
    PrefixRule { prefix: "TT", entity_id: "410", exact: false, priority: 10 }, // Chad
    PrefixRule { prefix: "TU", entity_id: "428", exact: false, priority: 10 }, // Cote d'Ivoire
    PrefixRule { prefix: "TX", entity_id: "512", exact: false, priority: 30 }, // Chesterfield Is.
    PrefixRule { prefix: "TX", entity_id: "036", exact: false, priority: 30 }, // Clipperton I.
    PrefixRule { prefix: "TX", entity_id: "509", exact: false, priority: 30 }, // Marquesas Is.
    PrefixRule { prefix: "TX0C", entity_id: "036", exact: false, priority: 60 }, // Clipperton I.
    PrefixRule { prefix: "TX0M", entity_id: "509", exact: false, priority: 60 }, // Marquesas Is.
    PrefixRule { prefix: "TY", entity_id: "416", exact: false, priority: 10 }, // Benin
    PrefixRule { prefix: "TZ", entity_id: "442", exact: false, priority: 10 }, // Mali

    // === U ===
    PrefixRule { prefix: "UA", entity_id: "054", exact: false, priority: 30 }, // European Russia
    PrefixRule { prefix: "UA0", entity_id: "015", exact: false, priority: 20 }, // Asiatic Russia
    PrefixRule { prefix: "UA1", entity_id: "054", exact: false, priority: 40 }, // European Russia
    PrefixRule { prefix: "UA2", entity_id: "126", exact: false, priority: 40 }, // Kaliningrad
    PrefixRule { prefix: "UA3", entity_id: "054", exact: false, priority: 40 }, // European Russia
    PrefixRule { prefix: "UA4", entity_id: "054", exact: false, priority: 40 }, // European Russia
    PrefixRule { prefix: "UA6", entity_id: "054", exact: false, priority: 40 }, // European Russia
    PrefixRule { prefix: "UA8", entity_id: "015", exact: false, priority: 40 }, // Asiatic Russia
    PrefixRule { prefix: "UA9", entity_id: "015", exact: false, priority: 20 }, // Asiatic Russia
    PrefixRule { prefix: "UB0", entity_id: "015", exact: false, priority: 40 }, // Asiatic Russia
    PrefixRule { prefix: "UB8", entity_id: "015", exact: false, priority: 40 }, // Asiatic Russia
    PrefixRule { prefix: "UB9", entity_id: "015", exact: false, priority: 40 }, // Asiatic Russia
    PrefixRule { prefix: "UC0", entity_id: "015", exact: false, priority: 40 }, // Asiatic Russia
    PrefixRule { prefix: "UC8", entity_id: "015", exact: false, priority: 40 }, // Asiatic Russia
    PrefixRule { prefix: "UC9", entity_id: "015", exact: false, priority: 40 }, // Asiatic Russia
    PrefixRule { prefix: "UI", entity_id: "015", exact: false, priority: 10 }, // Asiatic Russia
    PrefixRule { prefix: "UJ", entity_id: "292", exact: false, priority: 10 }, // Uzbekistan
    PrefixRule { prefix: "UK", entity_id: "292", exact: false, priority: 10 }, // Uzbekistan
    PrefixRule { prefix: "UL", entity_id: "292", exact: false, priority: 10 }, // Uzbekistan
    PrefixRule { prefix: "UM", entity_id: "292", exact: false, priority: 10 }, // Uzbekistan
    PrefixRule { prefix: "UN", entity_id: "130", exact: false, priority: 10 }, // Kazakhstan
    PrefixRule { prefix: "UO", entity_id: "130", exact: false, priority: 10 }, // Kazakhstan
    PrefixRule { prefix: "UP", entity_id: "130", exact: false, priority: 10 }, // Kazakhstan
    PrefixRule { prefix: "UQ", entity_id: "130", exact: false, priority: 10 }, // Kazakhstan
    PrefixRule { prefix: "UR", entity_id: "288", exact: false, priority: 30 }, // Ukraine
    PrefixRule { prefix: "US", entity_id: "288", exact: false, priority: 30 }, // Ukraine
    PrefixRule { prefix: "UT", entity_id: "288", exact: false, priority: 30 }, // Ukraine
    PrefixRule { prefix: "UU", entity_id: "288", exact: false, priority: 30 }, // Ukraine
    PrefixRule { prefix: "UV", entity_id: "288", exact: false, priority: 30 }, // Ukraine
    PrefixRule { prefix: "UW", entity_id: "288", exact: false, priority: 30 }, // Ukraine
    PrefixRule { prefix: "UX", entity_id: "288", exact: false, priority: 30 }, // Ukraine
    PrefixRule { prefix: "UY", entity_id: "288", exact: false, priority: 30 }, // Ukraine
    PrefixRule { prefix: "UZ", entity_id: "288", exact: false, priority: 30 }, // Ukraine

    // === V ===
    PrefixRule { prefix: "V2", entity_id: "094", exact: false, priority: 20 }, // Antigua & Barbuda
    PrefixRule { prefix: "V3", entity_id: "066", exact: false, priority: 20 }, // Belize
    PrefixRule { prefix: "V4", entity_id: "249", exact: false, priority: 20 }, // St. Kitts & Nevis
    PrefixRule { prefix: "V5", entity_id: "464", exact: false, priority: 10 }, // Namibia
    PrefixRule { prefix: "V6", entity_id: "173", exact: false, priority: 10 }, // Micronesia
    PrefixRule { prefix: "V7", entity_id: "168", exact: false, priority: 10 }, // Marshall Is.
    PrefixRule { prefix: "V8", entity_id: "345", exact: false, priority: 10 }, // Brunei Darussalam
    PrefixRule { prefix: "VA", entity_id: "001", exact: false, priority: 30 }, // Canada
    PrefixRule { prefix: "VB", entity_id: "001", exact: false, priority: 30 }, // Canada
    PrefixRule { prefix: "VC", entity_id: "001", exact: false, priority: 30 }, // Canada
    PrefixRule { prefix: "VD", entity_id: "001", exact: false, priority: 30 }, // Canada
    PrefixRule { prefix: "VE", entity_id: "001", exact: false, priority: 30 }, // Canada
    PrefixRule { prefix: "VF", entity_id: "001", exact: false, priority: 30 }, // Canada
    PrefixRule { prefix: "VG", entity_id: "001", exact: false, priority: 30 }, // Canada
    PrefixRule { prefix: "VK", entity_id: "150", exact: false, priority: 30 }, // Australia
    PrefixRule { prefix: "VK0H", entity_id: "111", exact: false, priority: 30 }, // Heard I.
    PrefixRule { prefix: "VK0M", entity_id: "153", exact: false, priority: 30 }, // Macquarie I.
    PrefixRule { prefix: "VK9", entity_id: "038", exact: false, priority: 40 }, // Cocos (Keeling) Is.
    PrefixRule { prefix: "VK9", entity_id: "171", exact: false, priority: 40 }, // Mellish Reef
    PrefixRule { prefix: "VK9C", entity_id: "038", exact: false, priority: 60 }, // Cocos (Keeling) Is.
    PrefixRule { prefix: "VK9C", entity_id: "037", exact: false, priority: 30 }, // Cocos I.
    PrefixRule { prefix: "VK9H", entity_id: "111", exact: false, priority: 60 }, // Heard I.
    PrefixRule { prefix: "VK9L", entity_id: "147", exact: false, priority: 30 }, // Lord Howe I.
    PrefixRule { prefix: "VK9M", entity_id: "171", exact: false, priority: 60 }, // Mellish Reef
    PrefixRule { prefix: "VK9N", entity_id: "189", exact: false, priority: 30 }, // Norfolk I.
    PrefixRule { prefix: "VK9W", entity_id: "303", exact: false, priority: 30 }, // Willis I.
    PrefixRule { prefix: "VK9X", entity_id: "035", exact: false, priority: 30 }, // Christmas I.
    PrefixRule { prefix: "VO", entity_id: "001", exact: false, priority: 30 }, // Canada
    PrefixRule { prefix: "VP0", entity_id: "235", exact: false, priority: 40 }, // South Georgia I.
    PrefixRule { prefix: "VP2E", entity_id: "012", exact: false, priority: 40 }, // Anguilla
    PrefixRule { prefix: "VP2M", entity_id: "096", exact: false, priority: 40 }, // Montserrat
    PrefixRule { prefix: "VP2V", entity_id: "065", exact: false, priority: 40 }, // British Virgin Is.
    PrefixRule { prefix: "VP5", entity_id: "089", exact: false, priority: 30 }, // Turks & Caicos Is.
    PrefixRule { prefix: "VP6", entity_id: "172", exact: false, priority: 10 }, // Pitcairn I.
    PrefixRule { prefix: "VP6/D", entity_id: "513", exact: false, priority: 30 }, // Ducie I.
    PrefixRule { prefix: "VP6D", entity_id: "513", exact: false, priority: 60 }, // Ducie I.
    PrefixRule { prefix: "VP6P", entity_id: "172", exact: false, priority: 60 }, // Pitcairn I.
    PrefixRule { prefix: "VP8", entity_id: "141", exact: false, priority: 30 }, // Falkland Is.
    PrefixRule { prefix: "VP8/G", entity_id: "075", exact: false, priority: 40 }, // Georgia
    PrefixRule { prefix: "VP8/H", entity_id: "241", exact: false, priority: 40 }, // South Shetland Is.
    PrefixRule { prefix: "VP8/O", entity_id: "238", exact: false, priority: 40 }, // South Orkney Is.
    PrefixRule { prefix: "VP8/S", entity_id: "240", exact: false, priority: 40 }, // South Sandwich Is.
    PrefixRule { prefix: "VP8F", entity_id: "141", exact: false, priority: 60 }, // Falkland Is.
    PrefixRule { prefix: "VP8G", entity_id: "235", exact: false, priority: 60 }, // South Georgia I.
    PrefixRule { prefix: "VP8H", entity_id: "240", exact: false, priority: 60 }, // South Sandwich Is.
    PrefixRule { prefix: "VP8O", entity_id: "238", exact: false, priority: 60 }, // South Orkney Is.
    PrefixRule { prefix: "VP8S", entity_id: "241", exact: false, priority: 60 }, // South Shetland Is.
    PrefixRule { prefix: "VP9", entity_id: "064", exact: false, priority: 30 }, // Bermuda
    PrefixRule { prefix: "VQ9", entity_id: "033", exact: false, priority: 10 }, // Chagos Is.
    PrefixRule { prefix: "VR", entity_id: "375", exact: false, priority: 10 }, // Philippines
    PrefixRule { prefix: "VR2", entity_id: "321", exact: false, priority: 20 }, // Hong Kong
    PrefixRule { prefix: "VU", entity_id: "324", exact: false, priority: 30 }, // India
    PrefixRule { prefix: "VU4", entity_id: "011", exact: false, priority: 30 }, // Andaman & Nicobar Is.
    PrefixRule { prefix: "VU7", entity_id: "142", exact: false, priority: 30 }, // Lakshadweep Is.
    PrefixRule { prefix: "VY", entity_id: "001", exact: false, priority: 30 }, // Canada

    // === W ===
    PrefixRule { prefix: "W", entity_id: "291", exact: false, priority: 20 }, // United States of America
    PrefixRule { prefix: "WH6", entity_id: "110", exact: false, priority: 30 }, // Hawaii
    PrefixRule { prefix: "WL", entity_id: "006", exact: false, priority: 30 }, // Alaska
    PrefixRule { prefix: "WL7", entity_id: "006", exact: false, priority: 40 }, // Alaska
    PrefixRule { prefix: "WP2", entity_id: "285", exact: false, priority: 40 }, // US Virgin Is.
    PrefixRule { prefix: "WP3", entity_id: "202", exact: false, priority: 30 }, // Puerto Rico
    PrefixRule { prefix: "WP4", entity_id: "202", exact: false, priority: 30 }, // Puerto Rico

    // === X ===
    PrefixRule { prefix: "XA", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "XA4", entity_id: "204", exact: false, priority: 40 }, // Revillagigedo
    PrefixRule { prefix: "XB", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "XB4", entity_id: "204", exact: false, priority: 40 }, // Revillagigedo
    PrefixRule { prefix: "XC", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "XC4", entity_id: "204", exact: false, priority: 40 }, // Revillagigedo
    PrefixRule { prefix: "XD", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "XD4", entity_id: "204", exact: false, priority: 40 }, // Revillagigedo
    PrefixRule { prefix: "XE", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "XE4", entity_id: "204", exact: false, priority: 40 }, // Revillagigedo
    PrefixRule { prefix: "XF", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "XF4", entity_id: "204", exact: false, priority: 40 }, // Revillagigedo
    PrefixRule { prefix: "XG", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "XG4", entity_id: "204", exact: false, priority: 40 }, // Revillagigedo
    PrefixRule { prefix: "XH", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "XH4", entity_id: "204", exact: false, priority: 40 }, // Revillagigedo
    PrefixRule { prefix: "XI", entity_id: "050", exact: false, priority: 30 }, // Mexico
    PrefixRule { prefix: "XI4", entity_id: "204", exact: false, priority: 40 }, // Revillagigedo
    PrefixRule { prefix: "XO", entity_id: "050", exact: false, priority: 10 }, // Mexico
    PrefixRule { prefix: "XQ", entity_id: "112", exact: false, priority: 20 }, // Chile
    PrefixRule { prefix: "XR", entity_id: "112", exact: false, priority: 20 }, // Chile
    PrefixRule { prefix: "XT", entity_id: "480", exact: false, priority: 10 }, // Burkina Faso
    PrefixRule { prefix: "XU", entity_id: "312", exact: false, priority: 10 }, // Cambodia
    PrefixRule { prefix: "XV", entity_id: "293", exact: false, priority: 10 }, // Viet Nam
    PrefixRule { prefix: "XW", entity_id: "143", exact: false, priority: 10 }, // Lao People's Democratic Rep
    PrefixRule { prefix: "XX9", entity_id: "152", exact: false, priority: 10 }, // Macao
    PrefixRule { prefix: "XY", entity_id: "309", exact: false, priority: 10 }, // Myanmar
    PrefixRule { prefix: "XZ", entity_id: "309", exact: false, priority: 10 }, // Myanmar

    // === Y ===
    PrefixRule { prefix: "YA", entity_id: "003", exact: false, priority: 10 }, // Afghanistan
    PrefixRule { prefix: "YB", entity_id: "327", exact: false, priority: 10 }, // Indonesia
    PrefixRule { prefix: "YC", entity_id: "327", exact: false, priority: 10 }, // Indonesia
    PrefixRule { prefix: "YD", entity_id: "327", exact: false, priority: 10 }, // Indonesia
    PrefixRule { prefix: "YE", entity_id: "327", exact: false, priority: 10 }, // Indonesia
    PrefixRule { prefix: "YF", entity_id: "327", exact: false, priority: 10 }, // Indonesia
    PrefixRule { prefix: "YG", entity_id: "327", exact: false, priority: 10 }, // Indonesia
    PrefixRule { prefix: "YH", entity_id: "327", exact: false, priority: 10 }, // Indonesia
    PrefixRule { prefix: "YI", entity_id: "333", exact: false, priority: 10 }, // Iraq
    PrefixRule { prefix: "YJ", entity_id: "158", exact: false, priority: 10 }, // Vanuatu
    PrefixRule { prefix: "YK", entity_id: "384", exact: false, priority: 10 }, // Syrian Arab Republic
    PrefixRule { prefix: "YL", entity_id: "145", exact: false, priority: 10 }, // Latvia
    PrefixRule { prefix: "YN", entity_id: "086", exact: false, priority: 20 }, // Nicaragua
    PrefixRule { prefix: "YO", entity_id: "275", exact: false, priority: 30 }, // Romania
    PrefixRule { prefix: "YP", entity_id: "275", exact: false, priority: 30 }, // Romania
    PrefixRule { prefix: "YQ", entity_id: "275", exact: false, priority: 30 }, // Romania
    PrefixRule { prefix: "YR", entity_id: "212", exact: false, priority: 10 }, // Bulgaria
    PrefixRule { prefix: "YS", entity_id: "074", exact: false, priority: 20 }, // El Salvador
    PrefixRule { prefix: "YT", entity_id: "296", exact: false, priority: 30 }, // Serbia
    PrefixRule { prefix: "YU", entity_id: "296", exact: false, priority: 30 }, // Serbia
    PrefixRule { prefix: "YV", entity_id: "148", exact: false, priority: 20 }, // Venezuela
    PrefixRule { prefix: "YV0", entity_id: "017", exact: false, priority: 30 }, // Aves I.
    PrefixRule { prefix: "YW", entity_id: "148", exact: false, priority: 20 }, // Venezuela
    PrefixRule { prefix: "YX", entity_id: "148", exact: false, priority: 20 }, // Venezuela
    PrefixRule { prefix: "YY", entity_id: "148", exact: false, priority: 20 }, // Venezuela

    // === Z ===
    PrefixRule { prefix: "Z2", entity_id: "452", exact: false, priority: 10 }, // Zimbabwe
    PrefixRule { prefix: "Z3", entity_id: "502", exact: false, priority: 30 }, // North Macedonia (Republic of)
    PrefixRule { prefix: "Z6", entity_id: "522", exact: false, priority: 30 }, // Republic of Kosovo
    PrefixRule { prefix: "Z8", entity_id: "521", exact: false, priority: 30 }, // South Sudan (Republic of)
    PrefixRule { prefix: "Z8", entity_id: "466", exact: false, priority: 10 }, // Sudan
    PrefixRule { prefix: "ZA", entity_id: "007", exact: false, priority: 30 }, // Albania
    PrefixRule { prefix: "ZB2", entity_id: "233", exact: false, priority: 40 }, // Gibraltar
    PrefixRule { prefix: "ZC4", entity_id: "283", exact: false, priority: 40 }, // UK Sovereign Base Areas on Cyprus
    PrefixRule { prefix: "ZD7", entity_id: "250", exact: false, priority: 10 }, // St. Helena
    PrefixRule { prefix: "ZD8", entity_id: "205", exact: false, priority: 10 }, // Ascension I.
    PrefixRule { prefix: "ZD9", entity_id: "274", exact: false, priority: 10 }, // Tristan da Cunha & Gough I.
    PrefixRule { prefix: "ZF", entity_id: "069", exact: false, priority: 30 }, // Cayman Is.
    PrefixRule { prefix: "ZK", entity_id: "170", exact: false, priority: 30 }, // New Zealand
    PrefixRule { prefix: "ZK3", entity_id: "270", exact: false, priority: 10 }, // Tokelau Is.
    PrefixRule { prefix: "ZL", entity_id: "170", exact: false, priority: 30 }, // New Zealand
    PrefixRule { prefix: "ZL7", entity_id: "034", exact: false, priority: 30 }, // Chatham Is.
    PrefixRule { prefix: "ZL8", entity_id: "133", exact: false, priority: 30 }, // Kermadec Is.
    PrefixRule { prefix: "ZL9", entity_id: "016", exact: false, priority: 30 }, // New Zealand Subantarctic Islands
    PrefixRule { prefix: "ZM", entity_id: "170", exact: false, priority: 30 }, // New Zealand
    PrefixRule { prefix: "ZP", entity_id: "132", exact: false, priority: 20 }, // Paraguay
    PrefixRule { prefix: "ZR", entity_id: "462", exact: false, priority: 30 }, // South Africa
    PrefixRule { prefix: "ZS", entity_id: "462", exact: false, priority: 30 }, // South Africa
    PrefixRule { prefix: "ZS8", entity_id: "201", exact: false, priority: 30 }, // Prince Edward & Marion Is.
    PrefixRule { prefix: "ZT", entity_id: "462", exact: false, priority: 30 }, // South Africa
    PrefixRule { prefix: "ZU", entity_id: "462", exact: false, priority: 30 }, // South Africa
    PrefixRule { prefix: "ZV", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "ZW", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "ZX", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "ZY", entity_id: "108", exact: false, priority: 30 }, // Brazil
    PrefixRule { prefix: "ZZ", entity_id: "108", exact: false, priority: 30 }, // Brazil
];

/// Look up the DXCC entity for a callsign
/// Uses longest prefix match with priority ordering
/// Returns ARRL 3-digit entity ID (e.g., "291" for USA)
pub fn lookup_callsign(callsign: &str) -> Option<&'static str> {
    let call_upper = callsign.to_uppercase();

    // Find all matching prefixes, sorted by prefix length (longest first) then priority
    let mut matches: Vec<&PrefixRule> = PREFIX_RULES
        .iter()
        .filter(|rule| {
            if rule.exact {
                call_upper == rule.prefix
            } else {
                call_upper.starts_with(rule.prefix)
            }
        })
        .collect();

    // Sort by prefix length (descending) then priority (descending)
    matches.sort_by(|a, b| {
        let len_cmp = b.prefix.len().cmp(&a.prefix.len());
        if len_cmp == std::cmp::Ordering::Equal {
            b.priority.cmp(&a.priority)
        } else {
            len_cmp
        }
    });

    matches.first().map(|rule| rule.entity_id)
}

/// Get all prefixes for a given entity
/// entity_id should be ARRL 3-digit format (e.g., "291")
#[allow(dead_code)]
pub fn get_prefixes_for_entity(entity_id: &str) -> Vec<&'static str> {
    PREFIX_RULES
        .iter()
        .filter(|rule| rule.entity_id == entity_id)
        .map(|rule| rule.prefix)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_us_callsigns() {
        assert_eq!(lookup_callsign("W1AW"), Some("291"));
        assert_eq!(lookup_callsign("K5ABC"), Some("291"));
        assert_eq!(lookup_callsign("N7XYZ"), Some("291"));
        assert_eq!(lookup_callsign("AA1BB"), Some("291"));
        assert_eq!(lookup_callsign("KB9FIN"), Some("291"));
    }

    #[test]
    fn test_us_territories() {
        assert_eq!(lookup_callsign("KH6ABC"), Some("110")); // Hawaii
        assert_eq!(lookup_callsign("KL7ABC"), Some("006"));   // Alaska
        assert_eq!(lookup_callsign("KP4ABC"), Some("202")); // Puerto Rico
        assert_eq!(lookup_callsign("KP2ABC"), Some("285")); // US Virgin Islands
    }

    #[test]
    fn test_caribbean_british() {
        assert_eq!(lookup_callsign("VP2MXY"), Some("096"));  // Montserrat
        assert_eq!(lookup_callsign("VP2EAB"), Some("012"));  // Anguilla
        assert_eq!(lookup_callsign("VP2VAB"), Some("065"));  // British Virgin Islands
        assert_eq!(lookup_callsign("VP5ABC"), Some("089"));  // Turks & Caicos
        assert_eq!(lookup_callsign("VP9ABC"), Some("064"));  // Bermuda
        assert_eq!(lookup_callsign("ZF1ABC"), Some("069"));  // Cayman Islands
    }

    #[test]
    fn test_caribbean_nations() {
        assert_eq!(lookup_callsign("V26ABC"), Some("094"));  // Antigua & Barbuda
        assert_eq!(lookup_callsign("V31ABC"), Some("066"));  // Belize
        assert_eq!(lookup_callsign("V47ABC"), Some("249")); // St. Kitts & Nevis
        assert_eq!(lookup_callsign("C6ABC"), Some("060"));   // Bahamas
        assert_eq!(lookup_callsign("6Y5ABC"), Some("082"));  // Jamaica
        assert_eq!(lookup_callsign("8P6ABC"), Some("062"));  // Barbados
        assert_eq!(lookup_callsign("9Y4ABC"), Some("090"));  // Trinidad & Tobago
        assert_eq!(lookup_callsign("9Y4DG"), Some("090"));   // Trinidad (bug report)
        assert_eq!(lookup_callsign("V47T"), Some("249"));   // St. Kitts (bug report)
        assert_eq!(lookup_callsign("J38ABC"), Some("077"));  // Grenada
        assert_eq!(lookup_callsign("J68ABC"), Some("097"));  // St. Lucia
        assert_eq!(lookup_callsign("J79ABC"), Some("095"));  // Dominica
        assert_eq!(lookup_callsign("J88ABC"), Some("098"));  // St. Vincent
    }

    #[test]
    fn test_caribbean_other() {
        assert_eq!(lookup_callsign("CO8LY"), Some("070"));   // Cuba
        assert_eq!(lookup_callsign("HI3ABC"), Some("072"));  // Dominican Republic
        assert_eq!(lookup_callsign("HH2ABC"), Some("078"));  // Haiti
        assert_eq!(lookup_callsign("FM5ABC"), Some("084"));  // Martinique
        assert_eq!(lookup_callsign("FG5ABC"), Some("079"));  // Guadeloupe
        assert_eq!(lookup_callsign("PJ2ABC"), Some("517")); // Curacao
        assert_eq!(lookup_callsign("PJ4ABC"), Some("520")); // Bonaire
        assert_eq!(lookup_callsign("PJ7ABC"), Some("518")); // Sint Maarten
        assert_eq!(lookup_callsign("P40ABC"), Some("091"));  // Aruba
    }

    #[test]
    fn test_central_america() {
        assert_eq!(lookup_callsign("TI2ABC"), Some("308")); // Costa Rica
        assert_eq!(lookup_callsign("TG9ABC"), Some("076"));  // Guatemala
        assert_eq!(lookup_callsign("HR2ABC"), Some("080"));  // Honduras
        assert_eq!(lookup_callsign("YN2ABC"), Some("086"));  // Nicaragua
        assert_eq!(lookup_callsign("YS1ABC"), Some("074"));  // El Salvador
        assert_eq!(lookup_callsign("HP1ABC"), Some("088"));  // Panama
    }

    #[test]
    fn test_south_america() {
        assert_eq!(lookup_callsign("YV5ABC"), Some("148")); // Venezuela
        assert_eq!(lookup_callsign("HK3ABC"), Some("116")); // Colombia
        assert_eq!(lookup_callsign("HC2ABC"), Some("120")); // Ecuador
        assert_eq!(lookup_callsign("HC8ABC"), Some("071"));  // Galapagos
        assert_eq!(lookup_callsign("OA4ABC"), Some("136")); // Peru
        assert_eq!(lookup_callsign("CP6ABC"), Some("104")); // Bolivia
        assert_eq!(lookup_callsign("CE3ABC"), Some("112")); // Chile
        assert_eq!(lookup_callsign("LU1ABC"), Some("100")); // Argentina
        assert_eq!(lookup_callsign("PY2ABC"), Some("108")); // Brazil
        assert_eq!(lookup_callsign("ZP5ABC"), Some("132")); // Paraguay
        assert_eq!(lookup_callsign("CX2ABC"), Some("144")); // Uruguay
    }

    #[test]
    fn test_japan() {
        assert_eq!(lookup_callsign("JA1ABC"), Some("339"));
        assert_eq!(lookup_callsign("JH1NBN"), Some("339"));
        assert_eq!(lookup_callsign("7K1ABC"), Some("339"));
    }

    #[test]
    fn test_germany() {
        assert_eq!(lookup_callsign("DL1ABC"), Some("230"));
        assert_eq!(lookup_callsign("DJ5XYZ"), Some("230"));
    }

    #[test]
    fn test_uk() {
        assert_eq!(lookup_callsign("G3ABC"), Some("223"));  // England
        assert_eq!(lookup_callsign("GM3ABC"), Some("279")); // Scotland
        assert_eq!(lookup_callsign("GW3ABC"), Some("294")); // Wales
    }

    #[test]
    fn test_hk0_san_andres() {
        // HK0 prefix should map to San Andres & Providencia (entity 216)
        assert_eq!(lookup_callsign("HK0ABC"), Some("216"));
    }
}